### ISSUE TITLE
Use composer to bring in as a dependency 

### ISSUE THREAD

**Issue by eddiejaoude** [justinwalsh/daux.io#131]
Run command from vendors/bin

Pass config via cli or have config outside project

**Comment by onigoetz** [comment]
This is working correctly now.

You can run

```
composer require justinwalsh/daux.io dev-development
```

I will merge this in the master branch very soon

and you will have a command named `vendor/bin/daux` available in your project.
It will generate the documentation from the `docs` folder in the current directory and put it in `static`
