### ISSUE TITLE
Validate that all the options a user pases in are options

### ISSUE THREAD

**Issue by BrandonOCasey** [justinwalsh/daux.io#145]
"ignore": {
        "folder": [ ".svn" ]
    },

should throw an error because it should be folders, so far that is all I have seen but there are probably more.

**Comment by onigoetz** [comment]
We will probably add some options validations, and we started to do it.

For your particular example, it's perfectly valid to name a file ".svn" so we would'nt be able to tell the right from the wrong in the configuration files
