### ISSUE TITLE
Generate PDF file out of entire documentation

### ISSUE THREAD

**Issue by TheSisb** [justinwalsh/daux.io#163]
Feature request.*

**Comment by m-baumgartner** [comment]
Any updates on this? I think that'd be a great step forward.

**Comment by dkisselev** [comment]
Sorry, but daux isn't really actively developed/maintained anymore so no real updates. (everyone that actively developed has gotten caught up with life, so it's tough to find time for it)

That being said, there's a handy Ruby gem called Gimli that can generate PDF's out of folders of md files.

Here's the github project: https://github.com/walle/gimli

And here's a sample .sh file on another project that I know of that uses Gimli really effectively: https://github.com/cleanflight/cleanflight/blob/master/build_docs.sh

(here's the folder structure that they have: https://github.com/cleanflight/cleanflight/tree/master/docs, and here's the output: https://github.com/cleanflight/cleanflight/releases/download/v1.7.2/Manual.pdf)

**Comment by m-baumgartner** [comment]
It looks good, i'll give this a try. Thank you very much for your detailed explanation.

**Comment by onigoetz** [comment]
Hello, I'm also interested by such a feature, I will look into it when I have some time

**Comment by brianjking** [comment]
+1 PLEASE! Thank you and keep up the awesome work...

**Comment by benelang** [comment]
+1 for this! @onigoetz do you have some good news for us?

**Comment by elliotevans** [comment]
Thanks, I will try Gimli. But same time is there any update on Daux.io pdf real-time rendering feature?

**Comment by onigoetz** [comment]
Hello,

This is not ready yet, but I made some improvements in the API last week that make it possible to render all content pages in order.

I still need to find something to convert HTML to PDF then I will be able to finalize that

**Comment by m-baumgartner** [comment]
@onigoetz Make sure to include [`wkhtmltopdf`](https://github.com/wkhtmltopdf/wkhtmltopdf) in your prospects. It's pretty popular in the community and has tons of formatting options.

**Comment by onigoetz** [comment]
Thanks for the link, I added it to my list, but Ideally I want to find a pure-php library.

I don't want to depend on anything external to create PDF files. but that will probably not be possible.

**Comment by onigoetz** [comment]
Hey, It's not finished yet, But I implemented a way to export files to a single HTML file.

```bash
./daux.phar -f html-file
```

The file will be generated inside the destination directory with the name `file.html`

By default that's `static/file.html`

With that you can print it out as a PDF, I will work on the actual PDF output.

**Comment by drreen** [comment]
+1! Looking for a Gitbook alternative

**Comment by Serdaro** [comment]
@onigoetz , Have you had the chance to look into the actual PDF output?

**Comment by onigoetz** [comment]
I'm closing this issue as the Daux project has been moved to https://github.com/dauxio/daux.io

As for the PDF generation, you can generate a singlepage documentation, but you'll have to export it manually to PDF currently
