### ISSUE TITLE
Using Invalid Characters in Navigation

### ISSUE THREAD

**Issue by karai17** [justinwalsh/daux.io#180]
Windows does not allowed some characters in filenames. Some of these characters, such as ":" are needed when documenting in some languages, such as Lua. Any idea on how to get these characters in?

**Comment by jersou** [comment]
**The Windows UTF-8 problem is fixed by PHP 7 usage**, I tested it and it works correctly as under Linux (and the generated files are identical). I had the same "Invalid Characters" with PHP 5.4.

@justinwalsh (or @dkisselev?) : I think you can update http://daux.io/Getting_Started#page_Install
> "Windows UTF-8 files support Files with UTF-8 characters cannot be handled on windows, this issue has no known fix yet."

**Comment by onigoetz** [comment]
Thanks for the information, I will update That page
