### ISSUE TITLE
Creating new pages from the webui

### ISSUE THREAD

**Issue by dkisselev** [justinwalsh/daux.io#187]
An extension to, #109, being able to create doc files server-side would be really useful.

**Comment by onigoetz** [comment]
For the moment the editor was removed to focus on the core and re-add the feature after the 1.0 version. I will add this to the 1.1 milestone

**Comment by onigoetz** [comment]
Closing this issue as we move the project to an organization: https://github.com/dauxio/daux.io, the packagist package name is now [`daux/daux.io`](https://packagist.org/packages/daux/daux.io) and we even have a [Docker image](https://hub.docker.com/r/daux/daux.io/).

If you are still interested by that feature, please open a new issue in the organization and we'll look into it.
