### ISSUE TITLE
Daux cleans target directory

### ISSUE THREAD

**Issue by flip111** [justinwalsh/daux.io#194]
Expected: replace target files leave the rest of the files alone

This can be a problem when the documentation points to file you want to keep in the same directory.

**Comment by onigoetz** [comment]
Is this still a request ?

If yes can you explain a bit more on why you would need that feature ?

Thanks in advance.

**Comment by flip111** [comment]
If you have files you refer to from the documentation which you want to keep in the same directory. Then every time you regenerate the documentation you would have to copy those files back into the directory (because they have been deleted). Which requires you to create additional scripts.

**Comment by onigoetz** [comment]
Now you can put any kind of files in the documentation source directory and they will be copied to the compiled documentation. Can you try it with the latest development branch ?

**Comment by onigoetz** [comment]
I close this as there is no news, you can put any type of file in the documentation source and it is tranferred on compilation
