### ISSUE TITLE
Enhanced markdown editor

### ISSUE THREAD

**Issue by camfindlay** [justinwalsh/daux.io#200]
The current textarea works well but could be enhanced to make editing and previewing changes a more pleasant user experience.

There are a couple of project out there that look interesting though given the bootstrap nature of daux, perhaps this could be a quick win in that area: https://github.com/toopay/bootstrap-markdown.

**Comment by onigoetz** [comment]
Yes I think a better markdown editor is clearly a good idea when we add it back, I will add this to milestone 1.1

**Comment by onigoetz** [comment]
Closing this issue as we move the project to an organization: https://github.com/dauxio/daux.io, the packagist package name is now [`daux/daux.io`](https://packagist.org/packages/daux/daux.io) and we even have a [Docker image](https://hub.docker.com/r/daux/daux.io/).

If you are still interested by that feature, please open a new issue in the organization and we'll look into it.
