### ISSUE TITLE
Suggest file name as heading be changed, duplicate headings.

### ISSUE THREAD

**Issue by camfindlay** [justinwalsh/daux.io#201]
While the idea is good, I find most *.md files for any documentation are already including an H1 heading at the top of the file, this leads to duplicate headings when displayed through daux.

Perhaps a heading from file name is only shown if the underlying markdown does not have H1 as it's first line?

**Comment by onigoetz** [comment]
Titles can be changed using a [Front Matter](https://dauxio.github.io/Features/Front_Matter.html)

By the way, the project has been moved to https://github.com/dauxio/daux.io, the packagist package name is now [`daux/daux.io`](https://packagist.org/packages/daux/daux.io) and we even have a [Docker image](https://hub.docker.com/r/daux/daux.io/)
