### ISSUE TITLE
Markdown metadata support?

### ISSUE THREAD

**Issue by Stolzenhain** [justinwalsh/daux.io#210]
Just wondering: Are there any plans to support YAML-style metadata in Markdown files, such as proposed by the [MultiMarkdown Syntax guide](https://github.com/fletcher/MultiMarkdown/wiki/MultiMarkdown-Syntax-Guide)?

There are several editors that support this sort of categorization as it tremendously helps organizing files/versions/dates/keywords on your files. 

As far as I know, several static site generators (e.g. [Pelican](http://docs.getpelican.com/en/3.3.0/getting_started.html#file-metadata)) / flat file CMSes (e.g. [Kirby](http://getkirby.com/docs/content)) use this approach.

**Comment by onigoetz** [comment]
That could be interesting, what would you like to add as metadata in your files ?

**Comment by Stolzenhain** [comment]
Hello! Glad you still had this on your radar – I recall this wasn't about enforcing some sort of strict document metadata (as in Pelican, eg. for document languages or tags) but more in the line of [an article by Hilton Lipschitz](http://hiltmon.com/blog/2012/06/18/markdown-metadata/) who uses custom metadata for self-organization. 

I adapted this approach for protocols, quotes and similar office notes, adding metadata as I felt, just to be able to search through the files.  

So instead enforcing Metadata (which comes with the added problem of enforcing a document language through the keys, eg. English), on could simply strip the metadata part and provide it as an expandable key/value info header, like in a mail header for example.

**Comment by onigoetz** [comment]
Interesting, I will investigate this, there are already libraries (like https://github.com/daylerees/kurenai) to separate metadata from the actual document, and adding them to the page seems fairly doable.

Even some of the metadata (description, tags) could be used for SEO or an internal search engine

**Comment by onigoetz** [comment]
Hi, I don't know if you're still interested in this, metadata support has landed in daux's `development` branch !

For the moment you can only access the data programmatically (via `getAttribute($name)` on the content)

But it also supports changing the page's title via attributes (if you want a special title, for example with underscores)

```markdown
title: How to use markdown_metadata
-----
Hi, I'm the content
```

**Comment by Stolzenhain** [comment]
Just tested it – cool! The perfect drop-in-solution for my heaps of tagged markdown textfiles. 
The `getAttribute()` approach seems fitting for a multitude of uses – you could basically wrap this around existing [Pelican](http://docs.getpelican.com/en/3.6.3/) notes and produce the same result – very handy indeed.

**Comment by onigoetz** [comment]
Thank you :D
