### ISSUE TITLE
Remove composer vendor directory from versioning

### ISSUE THREAD

**Issue by thasmo** [justinwalsh/daux.io#211]
Would it make sense to remove the composer vendor directory from versioning and add it to the .gitignore file? This means that people would need to run `composer install` first, after installing Daux.io, but it would make the project a little bit cleaner. For distribution there could be pre-configured packages/releases (ZIP archives etc.) for easy installation without composer.

Thoughts?

**Comment by onigoetz** [comment]
In the new version, the vendor folder is not there anymore and replaced by a `.phar` archive. This will even work with any php 5.4+ hosting environment.

We will also probably add downloadable releases on github
