### ISSUE TITLE
Give a way to specify static images folder

### ISSUE THREAD

**Issue by marienfressinaud** [justinwalsh/daux.io#236]
I've discovered Daux.io few days ago thanks to wallabag and I'm currently moving my documentation on it.

Actually I've a little problem: documentation is opened to contributions in [its self repository](https://github.com/FreshRSS/documentation) but only the ```./docs``` folder is visible. Since images have to be added in ```./img``` to be accessible and it is not visible in the repo, contributors have no easy way to add images.

I would like to specify another folder (e.g. in ```./docs/lang/img``` where lang could be ```en```, ```fr```, etc.) to get static images.

If you have no time to develop that, I may try to look at the source code to add this feature and then do a PR if you're interested.

**Comment by onigoetz** [comment]
this is now changed and the images can be in the same folder as the documentation, relative paths work correctly.

It is in the develop branch for now but will be in master very soon

**Comment by marienfressinaud** [comment]
Thanks but I moved to another system since I opened this ticket. But still, it's good to know ;).

**Comment by meghart** [comment]
@marienfressinaud Out of curiosity what system did you move to? I'm looking for a good docs editor and I haven't found anything.

**Comment by marienfressinaud** [comment]
@meghart I moved to MkDocs (http://www.mkdocs.org/). It's not totally the same usecase since it is a generator of static doc websites but it fits with my needs.
