### ISSUE TITLE
"generate.php" does not follows the "template" directive

### ISSUE THREAD

**Issue by korenanzo** [justinwalsh/daux.io#245]
Let me say that the templates management is a bit puzzling:
I  have understand that "template" into config.json does specifies the directory where the templates and themes are. It does not states the template to use, wich could be  stated into the theme.thm if not default. 
isnt 't it  puzzling? :) 

Anyway, when you understand it,  all things are ok, unless you want to change the defaults AND create a static site. In fact generate.php does not copy the custom directories that you could put under "daux.io/templates". sure, you could put your *custom* things under *default* but it does not sounds good ;)

RIc

**Comment by onigoetz** [comment]
Is this problem still the case?

I made some improvements in the develop branch and this should be far easier now. can you try it ?
