### ISSUE TITLE
Move 'Generated by Daux.io' to footer or allow removal

### ISSUE THREAD

**Issue by DannyBen** [justinwalsh/daux.io#248]
Although I am all for credits, I believe the the header is too prominent for such a line. I would be happier if it was in the footer and be a little more descriptive: "Documentation generated by Daux.io" - to avoid confusion if the site shows other thing that may have been generated (i.e. API).

Also, if it is in line with the author's attitude towards credit giving, I would consider adding an option in the config.json to remove it. Most people would probably keep it, but in some more sensitive cases, it may be desired to avoid having it.

**Comment by fern4lvarez** [comment]
+1

**Comment by brianjking** [comment]
+1. Any ETA or plans for this? Thanks!

**Comment by onigoetz** [comment]
@justinwalsh What do you think about this ?

**Comment by onigoetz** [comment]
Fixed in development branch, we moved the disclaimer to the left column.

**Comment by brianjking** [comment]
@onigoetz -- I currently have a copy of daux.io on the master branch, is there any way to merge this in? If so, how?

Thanks!

**Comment by onigoetz** [comment]
Hello,

currently we have a small problem with the merge to the master as it will deploy on our production server (Daux.io) but it has an older version of PHP and will break.

So for the moment I recommend you take the latest zip from the development branch.
