### ISSUE TITLE
Versioning daux.io and the documents seprately

### ISSUE THREAD

**Issue by BrandonOCasey** [justinwalsh/daux.io#252]
It would be really nice if we could version the "docs" folder separately from daux.io itself. This would make taking updates a whole lot easier for daux.io. There are two ways that I see this happening:
* We can add the docs folder to .gitignore, and move the current docs folder with examples, to an examples folder. daux.io would fall back to the example folder, unless a docs folder exists.
* We can add a config parameter in the global config to point to the location of the documents, this would mean that the global config would have to be changed to an example config, and more than likely used as a double fallback.

**Comment by TeckniX** [comment]
You can actually do this within the `global.json` config:

`"docs_directory": "/var/www/html/docs",`

**Comment by brianjking** [comment]
+1 Thanks!

**Comment by onigoetz** [comment]
You can also grab the `daux.phar` file now that doesn't need the `libs` and `vendor` folders anymore. making far less files to commit in your project
