### ISSUE TITLE
Is it possible to generate html files from markdown files that are created with daux.io?

### ISSUE THREAD

**Issue by vasili111** [justinwalsh/daux.io#253]
I need to include documentation in html format for offline viewing with software. Is it possible to generate html files from markdown files that are created with daux.io? If yes, how can I do it?

**Comment by PhilipTobias** [comment]
For more information, see my reply to the "generate.php is failing with only warnings #249" topic.

...pt

**Comment by jsumners** [comment]
I am confused as to why it doesn't only generate static files. Why would PHP even need to be involved?
