### ISSUE TITLE
<pre> into the body of article?

### ISSUE THREAD

**Issue by korenanzo** [justinwalsh/daux.io#254]
Hi ,
I'd like to write preformatted text into the main body of the page (I mean, the second column, aka the white part..) but if I use `<pre>` tag it acts as ``` and "drops" into the third column.

Is there a trick to do that?
Thanks,
Ric

**Comment by dkisselev** [comment]
As far as I know, there isn't a way to fully differentiate those cases, because of how the code floating feature works (its a CSS attribute on the pre tag itself)

If you can work with not having the third column at all, you can toggle the code floating feature off:

**Comment by korenanzo** [comment]
If only I had  a custom css!
Can I have a custom css, for example specified into docs/config.json ??

**Comment by korenanzo** [comment]
GOT IT :D

I've found that you can customize the theme.thm , adding all the files I want: I just added my own .css .

Thanks ,
RIc
