### ISSUE TITLE
Ordered list width

### ISSUE THREAD

**Issue by mschering** [justinwalsh/daux.io#255]
Is there a reason why the ordered list width is only 47%?

See the demo: http://daux.io/Examples/GitHub_Flavored_Markdown

I'd like them to stretch 100%. Is that something you are willing to change?

Thanks!

**Comment by dkisselev** [comment]
Is there a specific CSS element that you see that's forced to 47%? By default, daux shows that blue right bar for code blocks, which causes the text content to squish to about half the page (50% minus some additional padding could bring it to 47%).

There's a link labelled ```Show Code Blocks Inline``` in the left nav that will disable the code floating and let the content area take up 100%, is that what you're looking for?

**Comment by onigoetz** [comment]
This is a bug with the floating code blocks. We will look into it

**Comment by onigoetz** [comment]
Fixed in development branch
