### ISSUE TITLE
Mouse over on code block add extra space and scrollbar

### ISSUE THREAD

**Issue by yanosh-igor** [justinwalsh/daux.io#259]
When mouse over on block with code on right side appearing extra space in the bottom and scroll bar.
Here example http://take.ms/z1NuU
I am using Chrome. Please fix this issue.

**Comment by onigoetz** [comment]
We will try to reproduce that and fix it

**Comment by onigoetz** [comment]
I can't reproduce your issue and as we made a lot of theme fixes, we consider this fixed.

If you can reproduce this again with the latest develop branch, feel free to reopen this issue

**Comment by yanosh-igor** [comment]
Ok, thanks. Will upgrade and try it.
