### ISSUE TITLE
Unable to create default index page.

### ISSUE THREAD

**Issue by makailol** [justinwalsh/daux.io#260]
Hello,

First of all thanks for making this project opensource. It becomes easy to manage documents.

I have just started using this and trying to do some configuration. I want to make default landing page like http://ia3.ahoyworld.co.uk/ . Would you guide me how can I do it?

According to documentation, we just need to add _index.md in /docs/ but this doesn't seem to be working. It says page not found.

I have also tried to add index.md (renamed _index.md) in /docs/ directory but it doesn't seem to be working either. It says page not found.

Thanks,
Makailol

**Comment by tubia** [comment]
I'm experiencing the same problem.
`example.com/index` Return the `index.md` that is in the `root/` while `example.com` returns "Page not found".

**Comment by onigoetz** [comment]
Can you try with the new development branch ?

As this issue is old, I will close it, feel free to reopen it if your problem is still current
