### ISSUE TITLE
Is daux.io provide support for .net application documentation

### ISSUE THREAD

**Issue by sasmitapattnaik** [justinwalsh/daux.io#261]
Is Daux.io provide support for .net application documentation. If Yes kindly help us how to set up daux.io and use to create documentation of .net application.

**Comment by sasmitapattnaik** [comment]
Hi Can anybody help me on this

**Comment by dkisselev** [comment]
Hi,

Daux should work just fine for a .net application (the source code of your application doesn't even really matter that much).

It just depends on PHP. You'll need to figure out how to install PHP and a web server on your computer (for windows and Mac there's XAMPP, for Linux there are packages in most common repositories). Then you can extract the daux.io zip into your web root folder and browse to your localhost websiteto find daux.

Once you have that, you should be able to just place .md files into the daux/docs folder and they will appear in the daux interface. Code highlighting should work for .net without issues.

**Comment by sheetalinani** [comment]
If I place the daux.io zip into your web root folder how will i be able to run both application(.net) and daux(php) files?

**Comment by onigoetz** [comment]
@sheetalinani Please create separate issues for separate questions. Yes this should work, but you might need to configure your IIS server to work with both.
