### ISSUE TITLE
DauxHelper::configure_theme doesn't respect template name from config.json

### ISSUE THREAD

**Issue by mryanb** [justinwalsh/daux.io#262]
If the template is set to something other that default the paths for default.tpl and error.tpl are still set to the following:

>[template] => /Users/mbp/Sites/daux.io/templates/default/default.tpl
>[error-template] => /Users/mbp/Sites/daux.io/templates/default/error.tpl

**Comment by onigoetz** [comment]
The configuration is now changed, please check in the development branch. it will be soon merged to default
