### ISSUE TITLE
Textile support

### ISSUE THREAD

**Issue by philwareham** [justinwalsh/daux.io#272]
It would be great if this also supported [Textile](https://github.com/textile/php-textile) format. Is that feasible or is the architecture too strongly linked to Markdown?

**Comment by onigoetz** [comment]
That might be possible in the future.

For the moment the architecture is pretty tied to markdown, but as we are adding some extension systems, supporting other file types would be a good idea.

**Comment by philwareham** [comment]
Great, well thanks for considering! I'll keep an eye on future developments.

**Comment by onigoetz** [comment]
I'm closing this issue as the Daux project has been moved to https://github.com/dauxio/daux.io

You can add different format through Processors, I've successfully added other formats in the past like mustache, anything that can be compiled through a PHP library can be a processor.

https://dauxio.github.io/For_Developers/Creating_a_Processor.html
