### ISSUE TITLE
Invalid Characters in Navigation

### ISSUE THREAD

**Issue by senola** [justinwalsh/daux.io#276]
os: window 8
when i use characters  like chinese to the markdown name, something was wrong  
![qq 20150513151842](https://cloud.githubusercontent.com/assets/6022948/7605558/7f8f6a1e-f983-11e4-86f9-90734d62034e.png)

**Comment by wuweiit** [comment]
���ο�ʼʹ��  I also is. 
but this question how to resolve

**Comment by aleshkanet** [comment]
check this https://github.com/justinwalsh/daux.io/pull/286 i fixed this problem for me
![screenshot_7](https://cloud.githubusercontent.com/assets/2388747/8306099/e48ed878-19bd-11e5-86ed-1367c01a0e08.png)
