### ISSUE TITLE
Keep "_" in page title

### ISSUE THREAD

**Issue by creativejuiz** [justinwalsh/daux.io#278]
Hi Justin,

Thank you for your awesome work on Daux.io.
I'm actually testing your tool in a WordPress context, and would like to keep hook names in page title.
A hook is composed by words separated with "_". But it could also be a function name.

Instead of having "get the awesome thing()", I would like to see "get_the_awesome_thing()" in my nav menu. Is there a way to do something like that?

To do so, I tried to edit the `DauxHelper::get_title_from_filename` function like that: 

```php
public static function get_title_from_filename($filename) {
    $separator = ' ';
    $filename = explode('_', $filename);
    if ($filename[0] == '--') {
        $separator = '_';
        $filename[0] = $filename[1];
        unset($filename[1]);
    }
    if ($filename[0] == '' || is_numeric($filename[0])) unset($filename[0]);
    else {
        $t = $filename[0];
        if ($t[0] == '-') $filename[0] = substr($t, 1);
    }
    $filename = implode($separator, $filename);
    return $filename;
}
```

I know "-" is used to place the item at the end of the list, but this pattern could be replaced by "()" for example.
Now, my file name look like : "--_01_my_function().md".

Thanks for your help :)

**Comment by onigoetz** [comment]
We'll see if that's possible later, Daux relies a lot on the _ for file separation

**Comment by onigoetz** [comment]
Hi,
We added support for metadata in Daux, you can use that to create titles with an underscore : 

```markdown
title: How to use markdown_metadata
-----
Hi, I'm the content
```

This is the best we can do to support underscores in titles
