### ISSUE TITLE
template parameter in config.json not working

### ISSUE THREAD

**Issue by microcipcip** [justinwalsh/daux.io#280]
I am trying to edit the default template (not theme!) but it doesn't work and it seems there is no documentation that explain how to do it.

**Comment by onigoetz** [comment]
Is this this problem stil bothering you ? 
If yes, I invite you to try the new  development branch, the templates system is far easier to understand.

I will write the documentation on themes in a few days

**Comment by elliotevans** [comment]
Any update on new development branch?
