### ISSUE TITLE
Newly Created landing page not shown

### ISSUE THREAD

**Issue by yudhir** [justinwalsh/daux.io#281]
Getting PHP error . This is my First Run , Created A directory structure .. 05_Search -> index.md etc .
Search is shown but when I click on it it shows the following error. 
However Other Default folders Examples and Getting Started are working fine

Notice: Trying to get property of non-object in C:\xampp\htdocs\daux\libs\daux_page.php on line 172

Fatal error: Call to a member function get_url() on a non-object in C:\xampp\htdocs\daux\libs\daux_page.php on line 173

**Comment by onigoetz** [comment]
Can you please try the latest `development`branch ? your problem should be fixed in there.

I will close the issue, if you still encouter problems I will let you reopen it.
