### ISSUE TITLE
I have the float set to false but code blocks are still going to the right of the screen?

### ISSUE THREAD

**Issue by Spikechrisgaming** [justinwalsh/daux.io#282]
So i have a code block on one of my pages and i have float set to false but there still showing on the right side of the page?

**Comment by samvaughton** [comment]
Yeah this is happening to me too, any ideas? It is not too much of an issue at the moment.

**Comment by rain01** [comment]
check out case #246

**Comment by onigoetz** [comment]
I will close this as duplicated, please check #246 about advancement
