### ISSUE TITLE
Multilanguage file/folder problem

### ISSUE THREAD

**Issue by z--aszlo** [justinwalsh/daux.io#285]
In the configuration file one can make its documentation multi language, but I can't find how to add non-English pages/directories as it will yield a `Page Not Found` if I put a necessary accented character into the name of the page/folder. If there is no workaround for this I find the multi language option quite a bit misleading.
Is there a workaround for folders/pages with accents?

**Comment by aleshkanet** [comment]
Look at it https://github.com/justinwalsh/daux.io/pull/286. May be it can help you.

**Comment by onigoetz** [comment]
I will also look into this
