### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by wuweiit** [justinwalsh/daux.io#287]
We are in the team development, because the front of the staff on the interface, often to find a long time to find the corresponding interface, I hope the author can provide a search function.
A markdown document describes the multiple interfaces, hoping to join the anchor can quickly jump.

I hope *daux.io* can better! 

Thank you very much!

**Comment by onigoetz** [comment]
Thanks for your suggestions, search is one thing we would want to include; follow #18 for more informations
