### ISSUE TITLE
Add some checks on the quality of the code

### ISSUE THREAD

**Issue by onigoetz** [justinwalsh/daux.io#294]
Hi @justinwalsh @dkisselev @Gautham,

I write you to propose a few changes in the contribution process.

@justinwalsh : Can you please configure these tools ? As the owner you're the only one with enough acces for that.
- [x] Travis for our future unit tests : https://travis-ci.org/
- [x] Code Quality Check : https://scrutinizer-ci.com/
- [x] Verify Code Style: (PSR2): https://styleci.io/

And also create a `CONTRIBUTING.md` file to explain what we expect from our contributors like:
- follow PSR-2
- create pull requests to `development` branch

Also, @justinwalsh can you please check what goes on with my changes on the dev server ? it just gives a white page so it is not easy to debug :D

**Comment by dkisselev** [comment]
+1 on all counts

**Comment by onigoetz** [comment]
Oh and also add the project on https://packagist.org/ so that it can be added as a dependency

**Comment by dkisselev** [comment]
How would a packagist package work for live rendering of the docs? It could be useful for generation but I don't think the solution would be clean enough to publish regular docs unless there's some added documentation on how to do it.

**Comment by onigoetz** [comment]
Actually it's a request from #131 and it seems pretty feasible to me under 3 conditions : 
- use the current working dir to look for documentation instead of the basedir of Daux.io
- be able to set a directory as a source of themes. instead of only "resources"
- ability to specify the name of the documentation directory on the command line instead of global.json (would be a complement, not a replacement)

This would not work for the live version, but this is oriented for more advanced users who want to generate their documentation automatically on their continuous integration server.

**Comment by onigoetz** [comment]
and with https://getcomposer.org/doc/articles/vendor-binaries.md we could publish the generation command very easily

**Comment by onigoetz** [comment]
@justinwalsh any opinion on that ?

**Comment by onigoetz** [comment]
I added the checks on a fork of the project, that way I can add the hooks, I will add the badges on the Readme soon
