### ISSUE TITLE
Any way to serve on github pages?

### ISSUE THREAD

**Issue by hsdk123** [justinwalsh/daux.io#295]
Hi, I'd been searching for a documentation generator through markup and came along daux.io - is there any way to host the generated files on to github pages? 

I notice  http://couscous.io/ has a command to do so - I was wondering if daux.io has the same.

**Comment by onigoetz** [comment]
Yes there is a way to generate the documentation, just run the `./generate` command and you will get a folder containing all your static files ready to be deployed.

**Comment by onigoetz** [comment]
Just to precise what I said, the command should be run on the development branch, the master's branch command is `php generate.php`
