### ISSUE TITLE
Excessively large/heavy chevrons in title/breadcrumb

### ISSUE THREAD

**Issue by dkisselev** [justinwalsh/daux.io#296]
As seen on any sub-page, the chevrons that separate path segments are really large and bold compared to the text.

http://daux.io/More_Examples/Hello_World

**Comment by onigoetz** [comment]
Yes they are, I also think it's not that great. also, it's actually the only glyphicon we use, I'm not sure we want to load a font with dozens of icons just to use one.

**Comment by dkisselev** [comment]
Nope, we just needed breadcrumbs and that was the easiest way to do it in the moment (since we were already using Bootstrap and had the icon font loaded be default)

**Comment by onigoetz** [comment]
Fixed in development
