### ISSUE TITLE
Develpoment Testing

### ISSUE THREAD

**Issue by captainbinary** [justinwalsh/daux.io#298]
I have tried the development branch and i get errors all over the place.

The main index page shows this error:
```PHP
Warning: filemtime(): stat failed for docs\05_More_Examples\??????_???.md in phar://D:/xampp/htdocs/channelseeder/docs/daux.phar/libs/Tree/Builder.php on line 76
```

And once entering the documentation there is a critical error:
```PHP
Fatal error: Uncaught exception 'Todaymade\Daux\Exception' with message 'Could not locate file 'For_Developers/Creating_a_Processor'' in phar://D:/xampp/htdocs/channelseeder/docs/daux.phar/libs/Format/Base/ContentTypes/Markdown/LinkRenderer.php:41 Stack trace: #0 phar://D:/xampp/htdocs/channelseeder/docs/daux.phar/libs/Format/Base/ContentTypes/Markdown/LinkRenderer.php(67): Todaymade\Daux\Format\Base\ContentTypes\Markdown\LinkRenderer->resolveInternalFile('For_Developers/...') #1 phar://D:/xampp/htdocs/channelseeder/docs/daux.phar/vendor/league/commonmark/src/HtmlRenderer.php(80): Todaymade\Daux\Format\Base\ContentTypes\Markdown\LinkRenderer->render(Object(League\CommonMark\Inline\Element\Link), Object(League\CommonMark\HtmlRenderer)) #2 phar://D:/xampp/htdocs/channelseeder/docs/daux.phar/vendor/league/commonmark/src/HtmlRenderer.php(92): League\CommonMark\HtmlRenderer->renderInline(Object(League\CommonMark\Inline\Element\Link)) #3 phar://D:/xampp/htdocs/channelseeder/docs/daux.phar/vendor/league/commonmark/src/Block/Rend in phar://D:/xampp/htdocs/channelseeder/docs/daux.phar/libs/Format/Base/ContentTypes/Markdown/LinkRenderer.php on line 41
```

From what i can see it is looking in all the wrong folders. And to change this i would have to edit some obscure files hidden somewhere.

I have been trying the development branch as i have been having errors with landing pages and index pages in the master branch and i have been seeing comments saying
> Can you please try the latest developmentbranch ? your problem should be fixed in there.
> - onigoetz

**Comment by onigoetz** [comment]
From the path, I see you are on windows, I need to do some tests on windows, as there are other reported problems. I cannot guarantee it works for the moment. Do you have a linux/ os x machine ?

**Comment by captainbinary** [comment]
Ahh i see, didnt even consider that windows file systems would be playing up with it. Ofcourse it would, had a similar problem when i was doing a directory manager for a photo gallery.

I will test it on my Linux server later today and let you know the result. Thanks for the quick response.

**Comment by onigoetz** [comment]
Hi, did you have time to check on your linux server ?

**Comment by onigoetz** [comment]
Hi,
one of the two issues you reported is fixed, the other one has no known solution yet:
- The fatal exception is fixed, the page is generated correctly
- The `filemtime` error is still present, it is because the filename is utf8 and it is not supported on windows yet. We are still investigating on what might be causing this

**Comment by onigoetz** [comment]
Closing this as it seems there is no reliable way to support this on windows, instead use http://daux.io/Features/Front_Matter to set the title of your page and a filename that doesn't contain utf8 characters
