### ISSUE TITLE
Permit non .html link on static

### ISSUE THREAD

**Issue by Soullivaneuh** [justinwalsh/daux.io#302]
I made a `.htaccess` to permit link without `.html` extension.

This work but generated link has `.html` and I don't want to redirect each time...

Would be great to have on option for generate link without the html extension.

**Comment by onigoetz** [comment]
I will try to figure something out, but the objective of the generated version is that it can be seen offline easily, and removing the extensions would break that.

**Comment by Soullivaneuh** [comment]
> and removing the extensions would break that.

Can you please elaborate?

**Comment by onigoetz** [comment]
Let's say you have a page `content.md` it will then be generated to `content.html`

Now if you want to remove the `.html` at the end of the url there are two solutions:

## Remove all extensions in the URLs and add a rewrite rule in apache to add ".html" at the end of the urls
With this solution, the url in the document doesn't match any real file, so running it without an apache (or nginx) to do the rewrite, all your URL's are broken

## Remove all extensions in the URLs and remove the extension in the generated file.
With this solution, that would somehow work, but it would break in the way that the OS doesn't know how to handle that file.

**Comment by Soullivaneuh** [comment]
> so running it without an apache (or nginx) to do the rewrite, all your URL's are broken

I agree. But it's already the case for images. Path are wrongs.


What about an option of how to generate it ? In case of option setted to true, option one should be applied.

**Comment by onigoetz** [comment]
That's not true, the images should be inside the `docs` folder and upon generation, the image is copied.

Inside the markdown file you set a relative path to the image, and it will work correctly.
