### ISSUE TITLE
Plugins/extension support

### ISSUE THREAD

**Issue by atstp** [justinwalsh/daux.io#305]
I spent some time browsing, but didn't come across anything that pointed to plugin(esque) things.  Is there an existing way to do this that I might have missed? if not, what's the best way to approach it?

if it helps, I'm looking to tie in support for [this](https://github.com/atstp/wasabi) for documenting project structures.

**Comment by onigoetz** [comment]
Hello,
Actually, there is not exactly a support for plugin, but we support a thing we call "Processor" It's a class you can write that can extend some part of daux's generation.

It's documented in the "development" branch if you want to know more about it.

**Comment by gbaumgart** [comment]
+100 

would love to see that too. I do have an advanced file-manager and 'stack-edit' as plugin I would love to integrate: https://cloud.githubusercontent.com/assets/1205100/10619764/c138c86c-7777-11e5-8812-113be6fcb585.png. (in the mean-time I do edit files with github.com/gbaumgart/xamiro). 

I think its pretty simple to add support for plugins, in your renderer you would actually just need to emit some before/after events, allowing data to be manipulated....

**Comment by onigoetz** [comment]
Wow, your file manager looks pretty advanced.

I will think about it and see what I can come up with.

**Comment by gbaumgart** [comment]
as long i can insert links into pages its all done for me already :-) thanks.

to parse external plugin configs (as directory, via option), it might be enough to parse a directory for json files and instanciate found classes, later on you emit page events to that classes. (its already done in gbaumgart/xamiro/xapp/commander/pluginmanager or so). ... not that important :-)

**Comment by gbaumgart** [comment]
if you like i can write you a list of most-wanted callbacks for the 'plugin-api' ? Because after intensive working with daux and more complex environments, I can think of at least a few dozens. About the callback system itself, wordpress did it quite well btw. But hey, I know that any of them mean some work to you and I don't wanna bother you too much. 

I can spot 2 categories: 

- Directory/Files listing & reading: ie: add more files (from another directory), reject file, read file 
- Template callbacks (write head,body,resolve link etc...): ie: add more js/css, format nodes,...

...i wish i could help but i know to little...

**Comment by onigoetz** [comment]
Hi, yes, this could be useful if you had some kind of list. 

Actually, the first case you mentioned is already handled by the Processor, you can manipulate the tree the way you like in the Processor (I even created complete documentations just with this hook)

And the second case, you can implement your own templates, so in most cases, you can handle them easily already.

So the way I see it and to go in your direction, we can do three things : 
- Identify a list of callbacks that would really be useful for a plugin API
- Implement them in the current Processor API
- Improve the Processor API to be able to register multiple processors.

Does it fit with your vision ?

**Comment by gbaumgart** [comment]
yes!
on my way...

**Comment by gbaumgart** [comment]
ok, so after reading most code. Its fully enough to eventify these classes/methods or partials:


**Todaymade\Daux\Format\HTML\Template**

these methods are to eventify:

- render
- registerFunctions
- renderNavigation or buildNavigation


**Todaymade\Daux\Format\HTML\ContentPage**

- generatePage

**templates/layout/layout** 

Events in Head and Body in way that it is your markup, or the callback's result.
so it can append or replace these partials

**templates/home** and **templates/content**

same here


**Todaymade\Daux\Tree\Builder**

- isIgnored
- createContent

**Todaymade\Daux\Config**

not sure, where the config reader impl. is, but I'd like 
to write at any time in the config.   
   
**Todaymade\Daux\Tree\Directory**

not sure where, but as said we want add/reject new entries via callback every time a directory 
is being scanned. Of course, it needs another event when getting the virtual's file entry.

<hr/>

if you need with getting a simple pub/sub library (or AOP) injected(as trait or so) let me know. I think its per event just 1-2 lines but already quite powerful and enough.

About plugins it self, I'd prefer to fill just an directory with plugin classes. You load them and pass all along. When starting a plugin, I just hook in via sub. 

ok, that should be it.
thanks.

**Comment by onigoetz** [comment]
I'm closing this issue as the Daux project has been moved to https://github.com/dauxio/daux.io

As for this specific request, it's still on my mind but I won't implement it in the near future
