### ISSUE TITLE
Bug with multilanguage

### ISSUE THREAD

**Issue by tonetlds** [justinwalsh/daux.io#307]
I need to add a Portuguese language that have accentuation (like ç, ã, ó, etc), but I have this errors:
![capturar](https://cloud.githubusercontent.com/assets/2693019/9251479/cdca9f32-41a9-11e5-89c0-ef830cbf77ee.PNG)
![capturar2](https://cloud.githubusercontent.com/assets/2693019/9251481/cebcd892-41a9-11e5-8220-72c60d5cdecc.PNG)

How can I solve this?

**Comment by onigoetz** [comment]
Hi, normally this works correctly, do you use the master or development branch ?

**Comment by tonetlds** [comment]
Hi. I tried only the master branch.

**Comment by onigoetz** [comment]
Can you please try with the development branch ? we can't push on the
master for the moment for technical reasons.

The development branch is much more advanced and handles your case.

---
Stéphane Goetz
Développeur Web

http://www.onigoetz.ch

Mobile : +41 79/824.77.68
Mail : stephane.goetz@onigoetz.ch

**Comment by tonetlds** [comment]
I have several errors in the development branch... =P
First, with grunt I have this:
![image](https://cloud.githubusercontent.com/assets/2693019/9276573/385d674a-427b-11e5-941f-4ce2a8233f39.png)

And I tried with XAMPP, and...
![image](https://cloud.githubusercontent.com/assets/2693019/9278801/a5b61d24-4289-11e5-8192-55b05d34d6b2.png)

What I'm doing wrong?

**Comment by onigoetz** [comment]
I got it, you're on windows.

For the moment we have problems on windows. I will try to create a windows virtual machine to test it.

**Comment by onigoetz** [comment]
So, I had a change to make some tests on a windows virtual machine, it mainly works now, but not for your case sadly.

The support for utf-8 on windows is not good and we have no solution right now.

What I can recommend for the moment is to set a simple ascii name to your file, and in the next days I will add support for metadata in the core 
```
title: Introdução
---
Your very nice introduction here
```

This will allow you to have a correct title and still make it work on windows.

**Comment by onigoetz** [comment]
Sorry this took so long, Support for title via metadata is now implemented
