### ISSUE TITLE
First heading fails to render if no blank line at start of file

### ISSUE THREAD

**Issue by conficient** [justinwalsh/daux.io#308]
Testing DAUX I noticed some files were rendering as `# Heading` in normal text at the top, instead of `Heading`.

It seems that DAUX needs a blank line before the first markup to register it correctly? I added a blank line and this fixed it - is this intended behaviour?

**Comment by onigoetz** [comment]
Do you use the master or development branch ? I recommend using the development branch as it is much more advanced.

As for your bug report, normally, you can place a heading anywhere in the file, even on the first line, but the `<h1>` heading is handled by the name of the file

**Comment by conficient** [comment]
I am using the master branch, yes. I'll give the development branch a try.

I did try putting other entries in the first line, e.g. ## Heading but that also rendered as '## Heading' if there was no blank line at the top

**Comment by onigoetz** [comment]
Tested, this is fixed in the development branch

**Comment by conficient** [comment]
Thanks!
