### ISSUE TITLE
Development branch doesn't render

### ISSUE THREAD

**Issue by DeanDavis** [justinwalsh/daux.io#309]
I downloaded and installed the Master branch on my web server and it worked fine. Made no adjustments just did a simple FTP to my server. The example DOCS worked fine.
I had an issue with the Master Branch, that I did not file a report about, where an index.md at a folder level was not rendering.
I looked through the issues and they seemed to indicate I should install the development branch.
So, I download the dev branch and installed it complete as a test.
Nothing renders for me on a clean install. Total blank screen.
My server is a Mac running Apache 2.2.29 and php 5.4.34

**Comment by onigoetz** [comment]
Hi,
sorry for the long answer time, your version of php and apache should work with the development branch, can you enable logging or check in the apache error logs to see if there are more informations ?

as I can't reproduce your error on my machine I won't be able to help you out without an error message.

**Comment by onigoetz** [comment]
Hi, I made some fixes on the development branch for php 5.4, reopen the issue if you still get the problem
