### ISSUE TITLE
Markdown in Development branch

### ISSUE THREAD

**Issue by JayHoltslander** [justinwalsh/daux.io#311]
Is the built in markdown editor broken or removed in the development branch? Having trouble getting it working. Also noticed markdown rendering issues.

**Comment by onigoetz** [comment]
Hello,
yes the editor was removed for the moment, we want to stabilize what already exists and we will re-add the editor on a stable base. 

What rendering errors did you get ? 
We use `thephpleague/commonmark` for the rendering which is compatible with the latest commonmark specification.

**Comment by JayHoltslander** [comment]
Darn. I went to the development branch because apparently the image linking worked better. But if markdown doesn't work...
It sounds like Daux isn't quite ready for primetime. :-/ May have to look for an alternative solution.

The rendering error I got was headings weren't working. That's the only one I noticed.

**Comment by onigoetz** [comment]
Markdown rendering works fine.
One thing that happens sometimes with headers is that you put an unbreakable space between # and your title.

But that's in the markdown specification so it's not broken in daux
