### ISSUE TITLE
Markdown broken? 

### ISSUE THREAD

**Issue by mc007** [justinwalsh/daux.io#313]
Hi,
i updated to the last version and since then I do have trouble with headings: 

![image](https://cloud.githubusercontent.com/assets/1205100/9733165/69e500ea-5629-11e5-841e-41868e2c9cf3.png)

The markdown '###' is not rendered anymore correctly. Is there a trick? thanks!

**Comment by mc007** [comment]
ah, it needs a white space now

**Comment by onigoetz** [comment]
Hi, yes this is in the new Markdown reference.
