### ISSUE TITLE
Table header's visibility on vertical view

### ISSUE THREAD

**Issue by hiherman** [justinwalsh/daux.io#314]
When using HTML markup on mobile browser, table header appear only once, not on each row.
Second, when using MD,  table header doesn't appear.

![daux - header title not appear on each records](https://cloud.githubusercontent.com/assets/14918889/10212995/7684ab88-6831-11e5-80ad-9c759889e970.JPG)

**Comment by onigoetz** [comment]
I didn't even know we had some kind of responsive tables, I will investigate this when I get some time

**Comment by onigoetz** [comment]
After checking this seems the intended behaviour of the responsive table system, the only way to replicate the headers would be with Javascript and I don't plan to go in that direction for the moment.
