### ISSUE TITLE
Table's cell alignment

### ISSUE THREAD

**Issue by hiherman** [justinwalsh/daux.io#315]
Can it support these features ?

```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |
```

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

**Comment by onigoetz** [comment]
Hello, which branch are you using ?

on the development branch we use commonMark for markdown processing, and a plugin exists for that : https://github.com/webuni/commonmark-table-extension

If you want you can create a pull request for it, or you can add it for yourself in a Processor

**Comment by onigoetz** [comment]
Table support added with alignment on the `development` branch
