### ISSUE TITLE
Youtube/Instagram/facebook ribbon buttom

### ISSUE THREAD

**Issue by imuguruza** [justinwalsh/daux.io#316]
Is there any to add Youtube/Instagram/facebook ribbon buttom in the left side of the page?
I just tried to make it in the same way as twitter, with no luck:

(in the `config.json`)

```  
    "twitter": ["ErleRobotics"],
    "repo":["https://github.com/imuguruza/Docs"],
    "facebook": ["Iñigo Muguruza"],
    "youtube":["Iñigo Muguruza"],
```

**Comment by mjrev** [comment]
i guess, you should edit template to have ability to add github and facebook subscribe popup.
the only way now to implement is edit "links" section in `config.json`

**Comment by onigoetz** [comment]
as mjrev says, I would just edit the template to do that,
I will separate the templates in smaller pieces in the `development` branch to make it easier to do this kind of modifications
