### ISSUE TITLE
tables?

### ISSUE THREAD

**Issue by gbaumgart** [justinwalsh/daux.io#318]
Hi,
this here doesn't render a table: 

|Name|Description|Needs IDE|Mobile Support|Optimized|In Sync|LAN only|Opens anywhere|
|---|---|---|---|---|
|Open in new window|This mode is accessible in the file-manager through right click on the file, then click "Open in New Window"|yes|yes|no|yes|yes|yes
|Export as folder|This mode is accessible through the "Visual Editor" and exports all resources and dependencies, ready to be deployed anywhere.|no|yes|yes|no|yes|yes
|Export as application|This mode is accessible through the "Visual Editor" and exports all resources and dependencies |no|yes|optional|optional|optional|on installed devices.

Am I doing something wrong? , stackedit.io renders this correctly. 

thanks!

**Comment by mjrev** [comment]
```
|Name|Description|Needs IDE|Mobile Support|Optimized|In Sync|LAN only|Opens anywhere|
|---|---|---|---|---|---|---|---|
|Open in new window|This mode is accessible in the file-manager through right click on the file, then click "Open in New Window"|yes|yes|no|yes|yes|yes
|Export as folder|This mode is accessible through the "Visual Editor" and exports all resources and dependencies, ready to be deployed anywhere.|no|yes|yes|no|yes|yes
|Export as application|This mode is accessible through the "Visual Editor" and exports all resources and dependencies |no|yes|optional|optional|optional|on installed devices.
```
there should be the same number of dividers ( --- ) as columns. (you had 5, should be 8)

**Comment by gbaumgart** [comment]
that's what i thought too but no, fixing it makes no difference. I checked now also other docs and none of them shows tables anymore since upgrading to the last version (development) recently. 

I guess I will have to wait til development goes to master...

thanks.

**Comment by mjrev** [comment]
![table](https://i.imgur.com/5IfSS1n.png)
it renders ~~as fcuk~~
try to insert some newlines before and after table

**Comment by gbaumgart** [comment]
weird, I took a fresh copy but nothing shows up anymore (ubuntu-64 | php 5.5.9): 

git clone ....
git checkout development
cd daux.io
composer install
then open http://.....daux.io: 

 PHP Catchable fatal error:  Object of class FilesystemIterator could not be converted to boolean in phar:///PMaster/projects/x4mm/daux.io/daux.phar/libs/Tree/Builder.php on line 61

PHP Catchable fatal error:  Object of class FilesystemIterator could not be converted to boolean in /PMaster/projects/x4mm/daux.io/libs/Tree/Builder.php on line 61

'master' is fine...

**Comment by mjrev** [comment]
debian jessie, php 5.6.13

**Comment by gbaumgart** [comment]
Ok, what pity. We still have to maintain all at 5.3. Ok, thanks for your time! Actually its really strange because updating to development had no problems at all. Possibly one of the the composer deps cause the problem....who knows, php f*

**Comment by gbaumgart** [comment]
or can you confirm, daux.io is PHP 5.6 only ? We would to drop daux then.

**Comment by mjrev** [comment]
https://github.com/justinwalsh/daux.io#running-remotely

php 5.3 or higher required
php 5.4 for local server

**Comment by onigoetz** [comment]
Hello,
the `master` branch works on 5.3
but the `development` branch is more advanced and as php 5.3 and 5.4 are EOL : http://php.net/supported-versions.php they are not supported anymore

I have php 5.6 on my dev environment but I will make sure it also works for php 5.5, and if it's just a matter of a quickfix, I will also make 5.4 work fine.

**Comment by gbaumgart** [comment]
thumbs up!

**Comment by onigoetz** [comment]
So, I worked on it, Daux works on php 5.4, 5.5 and 5.6 on the development branch !
Enjoy ;-)

**Comment by onigoetz** [comment]
Actually, the development branch doesn't have tables support yet, I will work on that very shortly

**Comment by onigoetz** [comment]
Done, tables support is added in `development`

**Comment by mjrev** [comment]
that was fast :+1:

**Comment by gbaumgart** [comment]
not yet: 'Webuni\\CommonMark\\TableExtension\\TableExtension' not found in phar:///PMaster/projects/x4mm/daux.io/daux.phar/ ....

:-)

**Comment by onigoetz** [comment]
huh, okay, it seems my test was not made correctly, I'm sorry for that.

I will fix that tonight.

---
Stéphane Goetz
Développeur Web

http://www.onigoetz.ch

Mobile : +41 79/824.77.68
Mail : stephane.goetz@onigoetz.ch

**Comment by onigoetz** [comment]
I pushed a new version, tested correctly this time :D

**Comment by gbaumgart** [comment]
that was fast :+1: 

thanks a lot !!!
