### ISSUE TITLE
disable parent breadcrumb if there is no index file

### ISSUE THREAD

**Issue by mjrev** [justinwalsh/daux.io#320]
i just like menu animation when you click some item that has no index.md file inside it. but it this case it should have any other .md file. and this file has breadcrumb like `parent1 > parent2 > any.md`
as `parent2` doesn't have index.md in it, shouldn't it be right to disable that link to prevent "Page Not Found" page?
and...if it's possible, how can i apply that?

**Comment by onigoetz** [comment]
Hi,
is it on the `master` or `development` branch ?

I thought I fixed this on the `development` branch

**Comment by mjrev** [comment]
master. i checked development - yes, it's fixed. thank you
