### ISSUE TITLE
PHP 5.6 dependency now?

### ISSUE THREAD

**Issue by gbaumgart** [justinwalsh/daux.io#321]
Hi,
can someone confirm that daux.io (development) needs now PHP 5.6? Fresh checkouts on a 5.5.9 machine did crash somewhere. 

thank you.

**Comment by gbaumgart** [comment]
Dont bother, we switched to something else....what a waste of time again.

**Comment by onigoetz** [comment]
Hello,

I'm sorry we made you lose time, it should work on 5.5 but it seems we need to make a fix somewhere.

Out of curiosity, what did you switch to ?

**Comment by gbaumgart** [comment]
hi,
thanks for the heads up! Sorry for the lame comment, it was indeed frustrating. I will check again for a fix (i am sure its a tiny issue only). In the meantime I am looking at 'read the docs' (php is then totally out).

**Comment by onigoetz** [comment]
Hi,
Just so you know, I fixed the bug we had and now it works on php 5.4, 5.5 and 5.6
