### ISSUE TITLE
PHP Files 

### ISSUE THREAD

**Issue by VinceG** [justinwalsh/daux.io#322]
Not sure if this was discussed before. are there any plans of the ability to generate PHP files instead of HTML?

In some cases certain data within the markdown needs to be set based on the current page being displayed or in my case the titles/links needed to be different based on the current link being visited. 

I was able to do this myself by adding a new PHP content type generator extending from HTML with some minor changes to the source code. but this should be an easier implementation for others to write generators. currently the .html extension is hard coded in various places so even if you do add a new content type it fails unless those specific location where '.html' is located are modified. 

Thoughts?

**Comment by onigoetz** [comment]
Hi,

if you serve the files without generating them there is no ".html" extension appended and you can implement what you want at that moment.

But I don't understand what parts you want to be dynamic ? can you explain a bit further please ?

**Comment by VinceG** [comment]
@onigoetz For example, we have one documentation for a software running on different host addresses.

http://software1.com
http://software2.com
...

The documentation is hosted as static files on each host server

http://software1.com/documentation
http://software2.com/documentation
...

its the same copy of documentation we generated using the generate method for static files but hosted on each host.

In the documentation we reference links such as ```http://softwareX.com/api/...```

we would like to be able to set the link based on the current host address. if we visit
http://software1.com/documentation
the links in the documentation will reference
```http://software1.com/api/...```

http://software2.com/documentation
the links in the documentation will reference
```http://software2.com/api/...```

and so forth. this is just one example, but being able to use PHP within the markdown files and when parsing it'll execute the PHP code and save to a PHP static file it'll allow for more customization to be made.

Now, arguably this might be a very rare case and should not be implemented in the core functionality and i can understand that. I've already forked and modified the code to support that by adding a new PHP content type folder and doing some modifications to the existing source code to make this work as described.

I thought i'll just ask if others had the same idea or thoughts about this type of implementation and requirement. I am not expecting this to be implemented if there is really no use for others.

Thank You.

**Comment by onigoetz** [comment]
As you said, I think this is not a core use case and should be handled separately if that's what you want.

I'm not sure I understood everything perfectly, but I think that you can define your path to be relative to the root of the server, so the domain won't matter.

Also, all paths in Daux.io are relative, so I think this should be fairly easy to put in place for you.
