### ISSUE TITLE
float: true and <hr>

### ISSUE THREAD

**Issue by mjrev** [justinwalsh/daux.io#323]
when `float: true` and code blocks are shown (not inline) `<hr>` just goes to top of code column. if there are several of `<hr>` they are placed one below another. [example](https://i.imgur.com/TJ1MxvY.png)
this exists both - on master and on development branch

**Comment by onigoetz** [comment]
Hmm,
I will check that, it seems it is not normal ;-)

**Comment by onigoetz** [comment]
Fixed in the development branch
