### ISSUE TITLE
Add Mathjax support 

### ISSUE THREAD

**Issue by kdelwat** [justinwalsh/daux.io#324]
I really like the look of Daux, but I was wondering if it would be possible to add an option to add Mathjax support for rendering equations. The set-up process isn't very involved: basically just adding a line of JavaScript in the page head as detailed here: http://docs.mathjax.org/en/latest/start.html. Thanks!

**Comment by kdelwat** [comment]
[KaTeX](https://khan.github.io/KaTeX/) could also be a good option - it seems to load much faster than Mathjax.

**Comment by kdelwat** [comment]
Putting this section inside templates/default/default.tpl enables KaTeX autorendering. I'd submit a pull request for inclusion, but I'm not sure how to make it toggleable in the config.json file and I doubt it's a feature that everyone would want enabled all the time.
```
<!-- KaTeX -->
     <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.3.0/katex.min.css">
     <script src="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.3.0/katex.min.js"></script>
     <script src="//cdnjs.cloudflare.com/ajax/libs/KaTeX/0.3.0/contrib/auto-render.min.js"></script>
     <script>
          renderMathInElement(document.body);
     </script>
```

**Comment by onigoetz** [comment]
Hi,
thanks for the suggestion, I think we can add a line about that in the documentation, explaining how to customize the template to add this if someone wants it, I'm not sure we want to add this by default in Daux.io

What do you think of that idea ?

**Comment by kdelwat** [comment]
That sounds perfect - I agree that it shouldn't be a default feature.

**Comment by abhayghatpande** [comment]
Hi, I cannot find the file `template/default/default.tpl`. Where do I add the support for KaTeX or MathJax? Thanks.

**Comment by onigoetz** [comment]
This is probably what you're looking for : https://github.com/justinwalsh/daux.io/blob/master/templates/layout/00_layout.php

**Comment by abhayghatpande** [comment]
Thank you! That works. The script `renderMathInElement` has to be included in the `<body>`. The version of KaTeX is now 0.6.0.

Please help with issue #379 if you can. I've tried everything that I could think of.

**Comment by abhayghatpande** [comment]
So there seems to be a problem. The above method works only on the home page (`_index.md`). None of the subsequent pages render the math. The `content.php` uses the `05_page.php` layout. But that in turn calls the 00_layout.php. Not able to figure out why it won't render on other pages. Also tried the MathJax instead of KaTeX and it gives the same result.

**Comment by abhayghatpande** [comment]
Managed to fix it, but not sure why. I decided to use MathJax because I don't really have math-heavy pages, and it also needs just a single script to be included. I added the following in the `<article>` section of `content.php` and the `<head>` section of `00_layout.php`. 

```
<!-- LaTeX / Math Support-->
    <script type="text/javascript" async
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
    </script>
```

As I said, it works, but not sure why. Hope it doesn't break something else.

**Comment by onigoetz** [comment]
Closing this issue as we move the project to an organization: https://github.com/dauxio/daux.io, the packagist package name is now [`daux/daux.io`](https://packagist.org/packages/daux/daux.io) and we even have a [Docker image](https://hub.docker.com/r/daux/daux.io/).

If you are still interested by that feature, please open a new issue in the organization and we'll look into it.
