### ISSUE TITLE
Plans for supporting language specific syntax highlighting?

### ISSUE THREAD

**Issue by natanavra** [justinwalsh/daux.io#325]
There's code highlighting but it's not very detailed 
Like GFM's example:

```Objective-C
[[someObj method] anotherMethod];
```

\`\`\`Objective-C
[[someObj method] anotherMethod];
\`\`\`

**Comment by onigoetz** [comment]
Hi,
We use https://highlightjs.org/ for syntax highlighting.

It seems that we have an old version (8.0) and according to the changelog, 8.1 brings improvements in objective-c highlights.

I will update the library and let you know when it's updated

**Comment by onigoetz** [comment]
I pushed the latest highlightjs version on the `development` branch, can you test if it highlights the way you want?

**Comment by natanavra** [comment]
Hi,
I ended up using prism.js
Say, any reason why all of the css is smashed in a single file? Why not load it from CDNs? Makes it more modular and simpler to manage.

**Comment by onigoetz** [comment]
Yes, it is smashed in a single file for performance and portability reasons
We don't use a CDN because anyone can package it's own generated documentation without any external dependency
