### ISSUE TITLE
“Download as PDF” by rendering the markdown webpage

### ISSUE THREAD

**Issue by elliotevans** [justinwalsh/daux.io#327]
I have recently started using **duax.io** to create markdown based documentation for our website. 
Now I would like to know, what will be the simplest way to add “download as PDF” link/button on website, so that it will allow rendering the markdown webpage and downloading it in PDF format.  
* Can it be done by using **Pandoc** and **MiKTeX**? And how?
* Or it is only possible by converting markdown files into HTML and then using some command-line, script or utility?  
Any help will be greatly appreciated.

**Comment by onigoetz** [comment]
Hi, You want to download just a single page by PDF ?

I can print the page as pdf, we can tweak the styles to keep only the content.

I'm working on exporting all pages to one pdf you can follow that in issue #163

**Comment by pascalandy** [comment]
That might help !
https://gitprint.com/justinwalsh/daux.io/blob/master/README.md

**Comment by onigoetz** [comment]
I added new print styles in the dev branch. You can have a look at them on the dev branch : http://dev.daux.io
