### ISSUE TITLE
Edge and Tagged releases dropdown menu for switching between versions of documentation

### ISSUE THREAD

**Issue by signalpoint** [justinwalsh/daux.io#328]
Some documentation websites have a drop down menu that lets you specify which version of the software's documentation you'd like to browse For example:

 - Edge
 - 1.2
 - 1.1
 - 1.0

When chosen, you're able to then browse the tagged version of the software's documentation. Does daux.io have this feature?

I've poked around a bit, and I don't see much chat about this. I could see using the `generate` command when tagging a release, and then setting up the web server's document structure with something like:

```
/var/www/docs/
/var/www/docs/1.2
/var/www/docs/1.1
/var/www/docs/1.0
```

Then building a widget for the `config.json` which lets the author control the drop down menu. Of course it'd be awesome to automate this further, but I'd like to hear what others have done and/or think about this.

Thank you for this wonderful project.

**Comment by dkisselev** [comment]
I don't know what state the Language feature is in now, but it used to work well for this type of thing,

https://github.com/justinwalsh/daux.io#multi-language

Just define your releases as languages.
