### ISSUE TITLE
Document custom templates 

### ISSUE THREAD

**Issue by rarkins** [justinwalsh/daux.io#337]
As far as I can see, templates - or more importantly *custom templates* - remain undocumented? https://github.com/justinwalsh/daux.io/search?q=template&type=Code&utf8=%E2%9C%93 doesn't return any markdown files.

**Comment by onigoetz** [comment]
Hi,

I wrote a first documentation for that : http://daux.io/For_Developers/Creating_a_Theme

Tell me if it is useful to you and what I could improve.

**Comment by rarkins** [comment]
Thanks, I'll check it out and let you know once we start implementation

**Comment by gbaumgart** [comment]
i'd love to know how to switch "./templates" via config, is that possible already? btw. thanks for daux, got my docs now fully integrated, (still looking how to open things in surrounding electron app). [pics](https://github.com/net-commander/windows-dist/issues/24)

**Comment by onigoetz** [comment]
I'm not sure what you understand by "switch templates".

If you mean how to replace an embedded template with your template it's easy : create a file with the same name as the one in daux's `template` directory : https://github.com/justinwalsh/daux.io/tree/master/templates.

Thanks for the pics, really nice. what is net-commander/Control-Freak btw ?
