### ISSUE TITLE
how to prevent main Landing page 

### ISSUE THREAD

**Issue by vheun** [justinwalsh/daux.io#338]
Hi Guys,
is there any way how to prevent the confusing main landing page and go right in to the folder structure?
Either I get a "An error occured" or I get the landing page.
The documentation did not help me to figure it out.

Cheers,
V

**Comment by vheun** [comment]
Ok, I found a solution by basically copy the content from content.php to home.php in the templates folder. I don't know if this is the best solution?

**Comment by onigoetz** [comment]
Hi,
I just added an option to change that : http://daux.io/Features/Landing_page

You can grab the latest version and set the `auto_landing` option to false

**Comment by vheun** [comment]
Cool thank you!
