### ISSUE TITLE
Page goes blank w/o default docs folders

### ISSUE THREAD

**Issue by eric-miller** [justinwalsh/daux.io#340]
If I remove or replace the default document folders, when I reload the page it goes blank. I never removed _index.md and 00_Getting_Started.md in the folder while testing this as well.

**Comment by onigoetz** [comment]
Hello,
I'm not sure I follow what you're trying to do.
Which document folders are you removing/replacing ?

**Comment by eric-miller** [comment]
Just replacing the documentation that comes w/ the repo for my own documentation folders/.md files.
I've even tried adding them to the ignore list, and that causes the same issue. I ran it with grunt and was able to get an error on the page.

```
 Fatal error: Uncaught exception 'Todaymade\Daux\Exception' with message 'Could not locate file 'Features/Navigation_and_Sorting'' in phar:///Users/Eric/Servers/kmmfg/daux/daux.phar/libs/ContentTypes/Markdown/LinkRenderer.php:41 Stack trace: #0 phar:///Users/Eric/Servers/kmmfg/daux/daux.phar/libs/ContentTypes/Markdown/LinkRenderer.php(67): Todaymade\Daux\ContentTypes\Markdown\LinkRenderer->resolveInternalFile('Features/Naviga...') #1 phar:///Users/Eric/Servers/kmmfg/daux/daux.phar/vendor/league/commonmark/src/HtmlRenderer.php(80): Todaymade\Daux\ContentTypes\Markdown\LinkRenderer->render(Object(League\CommonMark\Inline\Element\Link), Object(League\CommonMark\HtmlRenderer)) #2 phar:///Users/Eric/Servers/kmmfg/daux/daux.phar/vendor/league/commonmark/src/HtmlRenderer.php(92): League\CommonMark\HtmlRenderer->renderInline(Object(League\CommonMark\Inline\Element\Link)) #3 phar:///Users/Eric/Servers/kmmfg/daux/daux.phar/vendor/league/commonmark/src/Block/Renderer/ParagraphRenderer.php(38): League\CommonMark\HtmlRenderer->renderIn in phar:///Users/Eric/Servers/kmmfg/daux/daux.phar/libs/ContentTypes/Markdown/LinkRenderer.php on line 41
```

**Comment by onigoetz** [comment]
Okay, I got it.

There is a feature to do internal links from a page to another. (http://daux.io/Features/Internal_links)

The `_index.md` and `00_Getting_Started.md` files both have links to `Features/Navigation_and_Sorting.md`.

And if you deleted this file, it will make an error.

If you change the links from these files, the errors are gone ;-)

**Comment by eric-miller** [comment]
Feature request:
It would be nice if a dead link didn't bring down the system.

Thanks for the help!

**Comment by onigoetz** [comment]
Well it's just the homepage, which happens to have that broken link.

It's the only idea I had to be sure the user knew the link is broken
