### ISSUE TITLE
generate fails

### ISSUE THREAD

**Issue by djohnanderson** [justinwalsh/daux.io#341]
I downloaded the latest stuff and was trying to generate the document on a mac.

./generate --help

fails to find vendor/autoload.php

Ok, I found that tree in an old version of daux.io then I get:

PHP Fatal error:  Class 'Todaymade\Daux\Console\Application'

Apparently generate is broken or the documentation is not clear about how to run it.

**Comment by djohnanderson** [comment]
Ok I figured it out. I need to install composer. It would be great if there were some more detailed doc on that.

**Comment by onigoetz** [comment]
Hi, composer is not needed actually.

By running `./daux.phar --help` you get the same as `./generate --help` but in a compressed archive which doesn't need composer or any kind of installation

**Comment by djohnanderson** [comment]
Nice tip!

I wasn't familiar with php archives, but I now see how that works.

I’ve been using daux.io and it’s working well. The only thing I missed was full text search which I managed to get going for the static sites using tipeusearch.

Thanks again,
John

**Comment by onigoetz** [comment]
Nice ! can you contribute that with a pull request ? I had plans to do exactly the same also with Tipue.

I'm sure many will like that feature.

BTW, if you changed the PHP in 'lib' you can run './bin/compile' and it will generate a new daux.phar file

**Comment by djohnanderson** [comment]
> On Jan 17, 2016, at 2:55 AM, Stéphane Goetz <notifications@github.com> wrote:
> 
> Nice ! can you contribute that with a pull request ? I had plans to do exactly the same also with Tipue.
> 
> I'm sure many will like that feature.
> 
> 

I can contribute it. I got it going with an old version of Daux.io and I also noticed there is a new version of Tipue. Also, I only needed it for the static site, so let me update it a bit and see if I can get it working with the dynamic site before I check it in.

John

**Comment by djohnanderson** [comment]
Hi Justin:

I’m getting pretty close to getting the the new Tipue search going with your latest version of Daux.io.

It was quite a bit easier than with the latest version because of the Processors feature, which I used to create the json index for Tipue. Also the way you break up templates and allow them to be added to a theme made it easy to add the UI. So far I am able to do everything without hacking the core code.

So far all this only works for export to HTML.

I do have a question: I need to copy the Tipue files and index to the destination directory. Originally I was thinking I could do that in the Processor, however, from the processor I can’t figure out how to get the output directory. I suppose I could add $input to the constructor of the Processor in prepareProcessor and lookup the destination option.

Alternatively it seems like the copying of the files belongs in the generator. I was thinking maybe I could subclass Todaymade\Daux\Format\HTML and override generateAll to copy the search files to the destination directory. However that requires that I specify a new format which doesn’t seem ideal.

I thought I’d get your opinion on the best way to go.

Let me know what you think.

Thanks,
John

**Comment by onigoetz** [comment]
Hi John,
Thank you very much for your work already, I can't wait to see what you've created.

For your question, there are two ways to achieve this.

1. The simple one : all files in the source directory (where the markdown files are) are copied over to the output directory, so if you add js, json, images or anything else, you will get it in the destination.
2. The programmatic one : for example, the content index you create live can be done with `Builder::getOrCreatePage` here's an example:

```php
<?php namespace Todaymade\Daux\Extension;

use Todaymade\Daux\Tree\Builder;
use Todaymade\Daux\Tree\Root;

class Processor extends \Todaymade\Daux\Processor {

    public function manipulateTree(Root $root)
    {
        $tipue = Builder::getOrCreatePage($root, 'tipue.json');
        $tipue->setContent(json_encode(['your_tree' => 'here']));
    }
}
```

The first parameter is the parent directory, the second is the file name.

And this will automatically create the file in the output directory, and also serve it in live mode.

If you want to use this feature, I discovered this morning some parts were missing, I fixed it this morning, so you need to download the latest code from the `development` branch.

**Comment by djohnanderson** [comment]
Hi Justin:

Thanks for the quick reply! I had considered the getOrCreatePage option and I think that’s a pretty nice solution for the index. I was wondering if there were any problems with the page not having a URI and all the other fields that content has.

My current approach was to add a directory named “tipuesearch” to the top level directory. It contains a small tree of files, javascript, css, images, etc for tipuesearch (I needed to modify the tipue javascript slightly). I was creating the index in that directory and then planning on recursively copying that entire directory to the destination. So the getOrCreatePage isn’t a great solution to recursively copying that tree.

After sleeping on it I’m leaning towards modifying the html generator to create the index and copy the tree of tipeu files to the output directory, perhaps adding an option to generate to include/exclude the search feature.

The index needs all the content so it makes the most sense for the static generator. The index is created once and loaded into the client browser cache and searched with javascript. Currently I’m creating the index with the markdown content since it’s smaller than the html, however I should probably be using markdown with the formatting striped out since two lines of it are shown below the search link. Alternatively I could use the generated html, but that’s pretty large — effectively the index become the size of the entire site.

Tipeusearch doesn’t make a lot of sense for the live mode — since the index is in the client instead of the server — and it needs all the content. So before searching, all the pages need to be generated, the index created and the index loaded into the client. I suppose I could come up with a scheme to only generate the index once the content becomes stale. But in the end, doing the search on the server makes the most sense for live mode.

For my current use the static mode is adequate.

Let me know your thoughts. After I get something that you can play with I’d appreciate your feedback on improving it.

And thanks for creating Daux.io. It’s a elegant compromise between features, flexibility and simplicity.

John Anderson

**Comment by onigoetz** [comment]
Hi again,

before answering your question, I am not Justin, I'm the current maintainer of Daux.io I had the need for a flexible and powerful, but still simple tool to create my documentations, and Daux.io was quite promising, but not really maintained. It seems you saw the same qualities as I did.

You're right, the most important is the static generator, even though I would like to see it in the live version (the daux.io website runs on the live version)

So in that case, you can modify Todaymade\Daux\Format\HTML directly, and add a configuration value to switch this value on or off. 

For the recursive copy of assets, I suggest you look at the `GeneratorHelper` class, it has a few methods to copy files.

I will be happy to review the changes you bring.

Stéphane

**Comment by djohnanderson** [comment]
Hi Stéphane:

Sorry I got you confused with Justin.

I finally got some time to get my search stuff ready for you to review.

I just pulled the development branch and added a branch off it called development-staticSearch under djohnanderson/daux.io.git where I pushed my changes.

I hope that’s enough information for you to look at it — I’m a bit new a contributing changes and writing php.

John

**Comment by onigoetz** [comment]
Hi John, no problem :D 

I created the pull request for you : https://github.com/justinwalsh/daux.io/pull/351
We can continue our conversation there.

I will try to review your changes this week and come back to you.
