### ISSUE TITLE
Page Titles with Project Name Included

### ISSUE THREAD

**Issue by signalpoint** [justinwalsh/daux.io#342]
I've got a simple page called `Hello World`, and the `<title>` ends up being:
```
<title>Hello World</title>
```
It'd be really nice if we could get the project name placed at the end of the page title for better SEO. I thought it would be possible by editing `templates/layout/00_layout.php` and placing this for the title:
```
<title><?= $page['title'] . ' | ' . $params['title']; ?></title>
```
This doesn't seem to work though, and upon page refresh I don't even see the `|` symbol. Is this possible, am I modifying the wrong file?

**Comment by onigoetz** [comment]
Hello, 

yes you're right we can add the Project name to the title.

It's completely normal that editing the files in the `templates` folder do not reflect on the generated pages if you use directly the `daux.phar` release without the `vendor` folder.

To change the template, follow the guide on custom themes : http://daux.io/For_Developers/Creating_a_Theme

**Comment by signalpoint** [comment]
@onigoetz Thank you, that worked. For others, use this terminal command from your daux root folder:

```
composer install
```

That allows your daux to run like a php app, as opposed to running through the `daux.phar` file which is pre-compiled and hence won't pick up any changes to the `templates` folder.
