### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by ayeo** [justinwalsh/daux.io#343]
Hi,

would you mind to tag some releases? I am using it on production and I wonder if I may just base on some stable release. I would love to upgrade version but I would like to decide my own when :) BTW great job! Thank you!

PS of course I can simply fork the project but stable release would be fantastic anyway :)

**Comment by onigoetz** [comment]
Hello, we're not quite sure we want to tag a 1.0.0 yet

but we can tag a 0.1.0 for the moment if that helps you ?

**Comment by ayeo** [comment]
That would by great for me. All I need is to base on unchagable version in my app build.

**Comment by onigoetz** [comment]
Hi, 0.1.0 is tagged

**Comment by ayeo** [comment]
Thank you!
