### ISSUE TITLE
Conflict between colons and tables

### ISSUE THREAD

**Issue by mlpadilla** [justinwalsh/daux.io#345]
Hi,

I have just spotted an issue where if a document contains colons before a table, the document is not displayed correctly. I made a simple example to illustrate this:

This is displayed correctly:
```

| a | b |
| --- | --- |
| 1 | 2 |

:

```
However, this is not displayed correctly:
```

:

| a | b |
| --- | --- |
| 1 | 2 |

```
If I use the HTML entity for a colon, it works:
```

&#58;

| a | b |
| --- | --- |
| 1 | 2 |

```
But obviously I would rather not replace all my colons by HTML entities.

Thanks!

**Comment by mlpadilla** [comment]
I forgot to say, most annoyingly anything before the table is truncated:
```

text1

:

| a | b |
| --- | --- |
| 1 | 2 |

text2

```

Cheers

**Comment by onigoetz** [comment]
Hi,

thanks for your report, this seems to be related to the markdown parser and tables, can you report that bug there please : https://github.com/webuni/commonmark-table-extension

**Comment by mlpadilla** [comment]
Sure, thanks.

If you would like to subscribe to the issue, [here I have reported it](https://github.com/webuni/commonmark-table-extension/issues/2).

**Comment by onigoetz** [comment]
Thanks, I will update as soon as there it is fixed

**Comment by hason** [comment]
All is alright, see https://github.com/webuni/commonmark-table-extension/issues/2#issuecomment-194887474.

**Comment by hason** [comment]
The problem is in https://github.com/justinwalsh/daux.io/blob/master/libs/Tree/Content.php#L103 It would be better to use the standard front yaml syntax and parser (e.g. [webuni/front-matter](https://packagist.org/packages/webuni/front-matter)).
