### ISSUE TITLE
Fatal Error when running Grunt to install Daux

### ISSUE THREAD

**Issue by vverzellesi** [justinwalsh/daux.io#347]
Hi

I'm trying to install Daux on my computer (Windows 7). I managed to download it and install all the requirements. However, when I run "grunt" command, so I access it through my localhost, I get the following error:

Fatal error: Call to undefined function League\CommonMark\Util\mb_strcut() in phar://C:/Users/MyUser/Desktop/documentation/daux.phar/vendor/league/commonmark/src/Util/RegexHelper.php on line 199

Any ideas on what am I missing?
Thanks!

@justinwalsh

**Comment by onigoetz** [comment]
Hello,
I'm sorry for the delay.

It seems that your installation of PHP doesn't have the mbstring extension, which is required by `league/commonmark`, the package we use to convert markdown to html.

I didn't use windows for PHP development in a few years, so I can't give you the answer on how to fix this easily, as it depends on how you installed your PHP.

Here are a few links that might help you : 
- http://php.net/manual/en/mbstring.installation.php
- http://www.knowledgebase-script.com/kb/article/how-to-enable-mbstring-in-php-46.html
