### ISSUE TITLE
New Sites for Demo Listing

### ISSUE THREAD

**Issue by signalpoint** [justinwalsh/daux.io#348]
I've deployed daux.io for documentation on 2 of my major open source projects, each has two major version releases. Here's some markdown if you'd kindly share these as examples in the demo list:

DrupalGap ([7](http://docs.drupalgap.org/7) | [8](http://docs.drupalgap.org/8))
jDrupal ([7](http://jdrupal.easystreet3.com/7) | [8](http://jdrupal.easystreet3.com/8))

Thank you to all for their work on daux.io, it really has changed the way I can manage and grow my open source projects!

**Comment by onigoetz** [comment]
Hello, thanks for your compliments and links.

I added them to the demos, I hope you don't mind I only added the Drupal 8 versions.

**Comment by signalpoint** [comment]
@onigoetz Perfect, thank you for your efforts.
