### ISSUE TITLE
how to use daux for jsp or java processor?

### ISSUE THREAD

**Issue by riveryong** [justinwalsh/daux.io#349]
I want to use daux for my company document website, but our website developed by jsp and java,
could you tell me how to use daux for jsp or java? thx,:)

**Comment by dkisselev** [comment]
Could you elaborate on what specifically you're trying to do?

Daux is written in/runs on PHP, so as long as you have a web server running PHP available, you just drop it into your www or webroot folder, and it should run.

Setting daux up to work side-by-side with a Java-based website/webapp is no different than any other PHP/Java setup, but it highly depends on exactly how your current website is set up and tends to be complex. The easiest solution might be to configure another server just for running PHP and setting up a subdomain that points to it (ie, docs.yourwebsite.com goes to the PHP server which serves daux).

It's possible to run them side-by-side but requires a lot of configuration and might be more trouble than it's worth.

Here's one example; the nginx web server has the ability to act as a reverse proxy/router, and you can configure it to route things to the appropriate server: http://techminded.net/blog/tomcat6-nginx-and-php-in-one-linux-box.html

With the configuration listed above, any request that ends in .php will be forwarded to PHP, and things ending in jsp (or under certain paths) will get forwarded to java.
