### ISSUE TITLE
Error When Generating Static Pages - Could not locate file

### ISSUE THREAD

**Issue by amadden734** [justinwalsh/daux.io#352]
If I have an internal link in one of my pages, but the page for that link has not been generated yet, I get 

`[Todaymade\Daux\Exception]
  Could not locate file 'Folder/Page'`

Is there a way to force the static generation so it won't fail?  It's not feasible to try and make sure that a page doesn't have an internal link to a page further down in the hierarchy.

**Comment by amadden734** [comment]
Anyone?

**Comment by amadden734** [comment]
Nevermind.  Looks like I just had the name of the link wrong.  Sorry!

**Comment by onigoetz** [comment]
Hello,

I'm really sorry I didn't answer sooner.

Just to add to your question, the resolution of the links is done to any other page, the order of generation is not important.

The process of generation (very simplified) is : 
- List all files and directories for the documentation
- Get the full hierarchy of pages in memory
- Render all pages.

So the rendering happens after the complete list was gathered.
