### ISSUE TITLE
Deleting default documentation throws PHP errors

### ISSUE THREAD

**Issue by tylerfoulkes** [justinwalsh/daux.io#356]
I feel like I am missing something simple but when I delete all of the default directories in the "docs" directory and I go back to the homepage PHP throws many errors, is there a file I need to move before deleting the default directories so that the homepage remains error free?

Any help would greatly appreciated.

**Comment by onigoetz** [comment]
Hello,
actually, you need at least two files in the `docs` directory : 
- `index.md` this is the homepage
- `anyothername.md` this is the documentation's first page.

When you get to the first homepage, you have a link "View Documentation", this link points to the first found page.

If this second file isn't found, it will crash

**Comment by tylerfoulkes** [comment]
Awesome, thank you! That worked perfect!
