### ISSUE TITLE
Issue with npm run build?

### ISSUE THREAD

**Issue by tylerfoulkes** [justinwalsh/daux.io#358]
I get the following error when I run the npm run build command, I am new to npm and Im not quite sure where the error is coming from?

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20

npm ERR! missing script: build
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /path/to/dauxio/project/npm-debug.log

**Comment by onigoetz** [comment]
Well, that's because npm run isn't supported on that project.

What were you trying to do ?

**Comment by tylerfoulkes** [comment]
O gotcha, I think I figured it out, I was just trying to run gulp but it seems it is as simple as just running the gulp command.
