### ISSUE TITLE
unreadable

### ISSUE THREAD

**Issue by gbaumgart** [justinwalsh/daux.io#363]
Hi 
have look at http://daux.io/Features/Landing_page. You will notice that parts of the text are hardly readable (too bright). Its really bad for the eyes to read long text with little contrast.

Where can we fix this?

**Comment by onigoetz** [comment]
Do you talk just about the text or also the code highlight ?

I can try to make it a bit more readable.

**Comment by gbaumgart** [comment]
look at "/docs" (link above) for instance. The same goes for code, yes. I created a custom theme to fix this but your less variables are not suited for changing the font color for these cases. So i did end-up by adding:

pre{
  background-color: initial;
}

But that is still not a solution since the top nav bar ends up bad too. However, try your self fixing this, you will see, its not that easy. 

Are you planning to change Bootstrap SASS sometime ?

**Comment by onigoetz** [comment]
No, I will probably not use sass, this would add a dependency to ruby. Two languages for development is enough in my opinion.
I will try to make a cleaner theme, I have some ideas, but they will take time to implement.

**Comment by gbaumgart** [comment]
SASS doesn't need Ruby anymore btw. and most good stock themes also build on SASS too. I had LESS for years and it never got really robust nor it was ever really satisfying, I guess that's why Twtitter dropped LESS for Bootstrap too.

anyway, Thanks for the heads up!

**Comment by gbaumgart** [comment]
SASS doesn't need ruby anymore btw. and most good stock themes also build on SASS. I had LESS for years and it never got really robust nor it was ever really satisfying. Anyway, matter of 'taste' i guess. 

Thanks for the heads up!

**Comment by gbaumgart** [comment]
I am actually trying to get this here for daux: https://wrapbootstrap.com/theme/light-blue-responsive-admin-web-app-WB0T41TX4 ([code](https://github.com/gbaumgart/bootrap-light-blue-admin-theme)). Its building already on the new SASS based Bootstrap version. If you like it, let me know, I can share that too.

**Comment by onigoetz** [comment]
Yes, if it's not ruby it's a binary, in both cases something special to install on top of the current stack.

And for the general usage, both SASS and LESS are fine. If we must change from one stack to another, I will most probably use Postcss, I use it in a few projects already and it's truly awesome.

Thanks for the link, though I'm not sure this is really more readable than the current theme.
For a theme with a good readability I was thinking of something like https://github.com/nijikokun/clarity

**Comment by onigoetz** [comment]
Hi,
I published optimizations of the current theme, what do you think about them ?

**Comment by onigoetz** [comment]
Hmm, there was a problem deploying, you can check the changes on http://dev.daux.io

**Comment by gbaumgart** [comment]
hi, not sure what you changed exactly but it seems more 'juicy'. The only thing I usually don't like is that I have a different background for code. It may look a little funky but I think its way more pleasant for your eyes when they need to switch for different backgrounds in such short time. Please keep in mind, documentation must work for short visits but also for hour long reading. What I also don't like at all are that code segments on the right, I prefer them always in line but I know, I can disable this. Just saying.

When working 8 hours or more, I use a bright themes for all my tools, and then switch to dark as soon its becoming dark outside too. I work now too long at the screen (20+ years) and it makes a big difference to please your eyes best as possible. I think I lost 20% of my sight already. 

:-)

I have btw. 4 for different color sets for the bootstrap theme I mentioned earlier (white, gray, blue transparent and almost black). I gonna add them soon as possible to daux, I am just struggling a little with with getting the daux classes ported over to SASS.

thanks for heads up.

**Comment by gbaumgart** [comment]
don't wanne discourage you: if think readthedocs made it all right: https://docs.readthedocs.io/en/latest/install.html. always easy to read text colors and nothing distracting on the screen 
:-)
