### ISSUE TITLE
Table titles are not shown in single column/responsive mode.

### ISSUE THREAD

**Issue by Aslai** [justinwalsh/daux.io#364]
When on a device with a small screen, the tables collapse into a narrower form which should display the title and content side by side. However, this is done with `attr(data-title)` in the `content` value for `td:before`, even though there are no such attributes in the generated `td` elements.

This could be a failing on the part of [webuni/commonmark-table-extension](https://github.com/webuni/commonmark-table-extension), as they might have exposed this functionality in the generator before and have since removed it. However, if that is the case, perhaps that functionality should be re-instated, either by a fork or a pull request to that repository.

**Comment by onigoetz** [comment]
You're right, this is actually a leftover of the theme. This feature was never completely implemented.

I will see if we can either, remove the styling, or add the feature to commonmark-table-extension

**Comment by onigoetz** [comment]
The responsive table feature was removed
