### ISSUE TITLE
Broken page in Examples/Code_Highlighting

### ISSUE THREAD

**Issue by OverFlow636** [justinwalsh/daux.io#366]
http://daux.io/Examples/Code_Highlighting

Not sure why but this page is malformed. its doing the same thing in the examples once cloned as well.

**Comment by onigoetz** [comment]
I see, this seems to be a bug with the front matter feature.
It swallows a big part of the page. I will write the test and the fix for this.

**Comment by onigoetz** [comment]
This is now fixed
