### ISSUE TITLE
bootstrap classes missing

### ISSUE THREAD

**Issue by gbaumgart** [justinwalsh/daux.io#370]
Hi,
can't tell why, but with the recent version of daux, most of Bootstrap classes are gone. In particular I am missing alert-info. I checked the gulp file and removed the  "unusedRules" sub tasks but the classes are still missing.

Any idea how to get all bootstrap classes back in my custom theme (copy pasted the default) ? 

thanks,
g

**Comment by onigoetz** [comment]
Some of the classes are removed with "unusedRules" and the other ones are removed by commenting the components in `bootstrap.less`

**Comment by gbaumgart** [comment]
yeah, turned out I had only to add bootstrap.less files in my theme. thanks for popping up!
