### ISSUE TITLE
override settings via url arguments

### ISSUE THREAD

**Issue by gbaumgart** [justinwalsh/daux.io#371]
Hi,
I didn't start searching myself yet but do you have by chance a pointer for me where I could implement an override for the theme and and docfiles settings of the config.json ? 

I use daux.io for lots of different documentations and over time it turned out would be more practical to just pass the theme and doc location to daux instead of going into some trickery. 

that's more of a silly question so feel free to close this :-)

as always, thanks a lot!

**Comment by onigoetz** [comment]
Hi,

to do something like that I would add some logic in the processor : https://github.com/justinwalsh/daux.io/blob/master/libs/Processor.php to be able to override the theme or other options.

maybe add a method `updateConfiguration` and pass it the raw configuration just after bootstrapping and before gathering the files.

**Comment by gbaumgart** [comment]
Thanks Stéphane,
gonna try that. 
g
