### ISSUE TITLE
Issue with UTF-8 BOM vs UTF-8

### ISSUE THREAD

**Issue by jessycormier** [justinwalsh/daux.io#372]
I've noticed that I was not able to use the following

    title: Hallo Welt
    date: 12th December 1984
    -------

When my file was set to this encoding "UTF-8 BOM", however changing the encoding to "UTF-8" fixed the issue. Is there a reason why the BOM is breaking this functionality ? (my code editor of choice defaults to always adding the BOM)

Im referring to this example page ( http://daux.io/Examples/Hello_World_de ) when changing it to UTF-8 BOM the title will be the original files title and not overridden.

**Comment by onigoetz** [comment]
Hi,
sorry for the long time before an answer.

I fixed the problem in the development branch

And by the way, In the current development version the format of the front matter changed a bit to:

```
---
title: Hallo Welt
date: 12th December 1984
---
```

**Comment by jessycormier** [comment]
Thanks for the update!
