### ISSUE TITLE
Server docroot returned 500-level response. Please check your configuration for possible errors.

### ISSUE THREAD

**Issue by kenlyon** [justinwalsh/daux.io#373]
**Steps to reproduce:**
1. Download the current daux.io-master.zip. (At time of writing, the last commit is 9b7b76a.)
2. Extract the archive.
3. Execute the command: `npm install`
4. Execute the command: `grunt`

**Expected result:**

The website should open in my browser.

**Actual result:**

It aborts with the following warning:

`Warning: Server docroot returned 500-level response. Please check your configuration for possible errors. Use --force to continue.`

See [attached full output](https://github.com/justinwalsh/daux.io/files/287357/daux.io.Error.Message.txt)

**Additional information:**

This was introduced by commit [2c3042a](https://github.com/justinwalsh/daux.io/tree/2c3042a2f376ec1c8c61034fd3f2f70ba43bafac).

**My environment:**
- Windows 10 Pro (64-bit)
- PHP v5.4.45
- node.js v4.3.1
- grunt-cli v2.14.12

**Comment by onigoetz** [comment]
Hello, actually, grunt is the old way of running it, the best is to simply run  `php -S 0.0.0.0:8085 index.php` (normally that would be `./serve` but as you are on windows, this won't work.)

Grunt and gulp are just wrappers around that command.

**Comment by kenlyon** [comment]
I don't think port `0.0.0.0` works on Windows, so I tried `php -S 127.0.0.1:8085 index.php` in addition to `0.0.0.0`.

The command window did not show the warning, but then it also didn't try to open the page for me. When I attempted to connect to the page via my browser using http://127.0.0.1:8085/ (http://0.0.0.0:8085/ does not work in my browser) I got a 500 response like before.

This would suggest that the problem is deeper in the code and isn't limited to the use of grunt.

**Comment by onigoetz** [comment]
I had a look with the latest version (0.2.1) on windows and it works fine with `php bin/daux serve` (the new way to run daux)

So I'm closing this issue, please reopen it if you encounter this issue again

**Comment by kenlyon** [comment]
I tried again using the latest copy of master. (Latest commit is 57f3111) I get the same result.

>php bin/daux serve

and

>php -S 127.0.0.1:8085 index.php

both give me the same result. Opening <http://127.0.0.1:8085/> in my browser gives a blank response with a status code of 500.

If it works for you, perhaps something is different with my environment. Do I need to upgrade any of the items I listed in my initial post?

**Comment by onigoetz** [comment]
Okay, I think we need to figure out why the page is blank and why you don't see the error messages.
Can you check in your `php.ini` to have `display_errors` set to `On`.

If you can't change your ini file, you can add this snippet to the beginning of the `bin/daux` file, (it's a text file) just after the `<?php` opening tag.

```php
ini_set('display_errors', 'On');
error_reporting(-1);
```

About your environment I think it should work fine.
- We established it's not linked to node/grunt/gulp.
- I tested it on windows recently and it works.
- Daux should still work on php 5.4 even if composer will refuse to install dependencies on a version older than 5.5

I suspect there is a missing PHP Extension. but we'll find out once you can see the exact error message.

**Comment by kenlyon** [comment]
Thanks for the suggestions. Here's what I found.

When I run the `php bin/daux serve` command, I see this error message in the console:

```Warning: chdir(): Invalid argument (errno 22) in phar://C:/daux.io-master/daux.phar/libs/Console/Serve.php on line 41```

The error displayed on the page is:
<br />
<b>Warning</b>:  Unknown: failed to open stream: phar error: &quot;index.php&quot; is not a file in phar &quot;C:/daux.io-master/daux.phar&quot; in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Fatal error</b>:  Unknown: Failed opening required 'phar://C:/daux.io-master/daux.phar/libs/Console/../..//index.php' (include_path='.;C:\php\pear') in <b>Unknown</b> on line <b>0</b><br />

I don't know the purpose of daux.phar, but it seems like it shouldn't be included in these paths.

**Comment by onigoetz** [comment]
I'm closing this issue as the Daux project has been moved to https://github.com/dauxio/daux.io

If you still encouter this issue with the latest version (0.8.0) I encourage you to report it in the new repository.
