### ISSUE TITLE
Tab character no longer working for nested lists

### ISSUE THREAD

**Issue by kenlyon** [justinwalsh/daux.io#376]
**Steps to reproduce:**

1. Download and install daux.io.
2. Open the "docs/00_Getting_Started.md" file in a text editor.
3. Add a **tab character (not four spaces)** to the start of any bullet point
**except the first one in a list**.
4. Launch the website.
5. Click on the **View Documentation** button to view the "Getting Started" page.

**Expected result:**

The edited line should be indented one level.

**Actual result:**

The edited line is appended to the end of the previous line, with the *
character rendered literally, not as a bullet.

**Additional information:**

This was introduced by commit 9a615ea.

Is this an intended deprecation of tabs or was this behaviour introduced by
accident? I realize tabs aren't officially supported in markdown, but our team
also edits in gitlab, which does support tabs. It'd be great if tabs were still
accepted here.

**My environment:**

- Windows 10 Pro (64-bit)
- PHP v5.4.45
- node.js v4.3.1
- grunt-cli v2.14.12

**Comment by onigoetz** [comment]
Thanks for your report, I will look into this, the commit you are referring to follows an update to commonmark 0.13.2 from 0.13.0 which contains the following PR : thephpleague/commonmark#234 

This seems to change the behaviour with tabs.

Can you please provide me the example as a gist so I can make further tests with it ?

**Comment by kenlyon** [comment]
I've attached a basic example. The tab character was previously treated the same as four spaces, allowing sub list items to be defined as demonstrated in the attachment. In the same example, I also included a sub list item defined with four spaces to allow a comparison.

[example.txt](https://github.com/justinwalsh/daux.io/files/312759/example.txt)

**Comment by onigoetz** [comment]
I opened an issue directly in the commonmark project about this : thephpleague/commonmark#258 We'll see what they can do about it

**Comment by onigoetz** [comment]
Okay so this error is fixed in commonmark, I will close this once the fix is released.

**Comment by onigoetz** [comment]
`league/commonmark` 0.15.0 was released with the fix, but because of `webuni/commonmark-table-extension` we can't update just yet.

I create the following pull requests to them:

webuni/commonmark-twig-renderer#3
webuni/commonmark-table-extension#5
webuni/commonmark-attributes-extension#5

**Comment by hason** [comment]
@onigoetz I published a new version of `webuni/commonmark-table-extension`.

**Comment by onigoetz** [comment]
Awesome, thanks @hason
