### ISSUE TITLE
multi-language not working

### ISSUE THREAD

**Issue by tropicalpb** [justinwalsh/daux.io#377]
I use the default project, made a few minor edits, and folder structure is below.

docs/
\ \ _index.md
\ \ config.json
\ \ en/
\ \ \ \ 00_Getting_Started.md
\ \ \ \ 01_Features/
\ \ \ \ \ \ GitHub_Flavored_Markdown.md

and in config.json
{
    "title": "...",
    "tagline": "...",
    "author": "...",
    "image": "",
    "languages": { "en" : "English" },
   ...
}

when I run ./generate -c docs/config.json -d ./output/, get the exception below
Copying Static assets ...                                             [  OK  ]
Generating ...
- index.html                                                          [  OK  ]
- en/Getting_Started.html                                             [ FAIL ]

                                                             
  [Todaymade\Daux\Exception]                                 
  Could not locate file 'Features/GitHub_Flavored_Markdown'

**Comment by onigoetz** [comment]
Hello, this means that the link inside "Getting_Started" referring to "Features/Github_Flavored_Markdown" is broken, try to change the link to "en/Features/Github_Flavored_Markdown"

**Comment by tropicalpb** [comment]
This seems to be incompatible with the typical web link design.  First, shouldn't the link be relative to where the referenced page is unless specifically using / at the top of links?  if all links need to be from the top level, then all localized reference need to add the language specific folder name, making documents linking messy.

Second issue I have discovered is that, in order to make the left-side menu appear in the language of the choice, I need to change the file name to hat language as well, This is difficult to manage.  Can there be some element in the document that controls the name with which it appears in the left side menu so that file names are all identical in localized folders.

**Comment by onigoetz** [comment]
Yes, I agree it's far from perfect, @gbaumgart also raised an issue about links in issue #374

I will have a more in-depth look into how links work in order to make relative links work fine

**Comment by onigoetz** [comment]
For your second issue, I just discovered that I didn't document this feature.

You can add a front-matter to your Markdown file :

```
title: Your translated title
-----
Your content here
```

This title will take precedence on the file name

**Comment by tropicalpb** [comment]
great, file name title does work.  However, how would the folder name be provided a translated title?

**Comment by onigoetz** [comment]
Request moved to #397
