### ISSUE TITLE
Just unzipping the daux.io-master.zip on a PHP enabled webserver does not work

### ISSUE THREAD

**Issue by abhayghatpande** [justinwalsh/daux.io#379]
I tried this on both Mac OS and Ubuntu. PHP is installed and working. `mod_rewrite` is installed and configured.

When I run the included `./serve` command the site works without problem. 

But not without it. Only the index page is displayed and none of the following pages are rendered. It makes me think that some step is missing when using a webserver. Please help.

**Comment by onigoetz** [comment]
Hi,
I will try to have a look at it soon, I see you mentioned `mod_rewrite` so I'm assuming you're on Apache HTTP.

**Comment by abhayghatpande** [comment]
Yes, it's Apache. 

For every URL it's the dreaded 404 Not Found error.

**Comment by abhayghatpande** [comment]
Solved! The problem on Mac was that the `AllowOverride All` directive is required in both the `/etc/apache2/users/username.conf ` and the `/etc/apache2/extra/httpd-vhosts.conf` files.

In my case it was active in the vhosts file, but not in the user file. Sorry for all the trouble.

Now need to figure out how it works with Lighttpd.
