### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by absolutejam** [justinwalsh/daux.io#391]
Hey guys, sorry to post an issue on this as I know it's probably my inexperience, but I wonder if you can help me get up and running.

I'e installed daux.io via `composer global require justinwalsh/daux.io` (and some of the dependencies that  didn't get installed automatically), and it's now living in `~/.config/composer/vendor/justinwalsh/daux.io`. Now, I can add this to my path, but I still can't run a `daux` command, only the individual commands such as 'serve'. Am I going about this completely wrong?

I can run the mentioned `serve` command and it'll start a web server, but then if I connect, I get `Unknown: Failed opening required 'index.php' ...`. 

I've used other projects like Jekyll before and I assume I'd have to do the same - Create the base directory then run `daux serve` (Or something like that) - which is in my path env var - from within my daux directory.

Any help would be appreciated.
Thanks!

**Comment by onigoetz** [comment]
Hi,

What missing dependencies are you referring to ? If there are some, I can add them to the composer.json

The `daux` command is inside `.../justinwalsh/daux.io/bin`. If I understand correctly, the `serve` command you're referring to is an old shortcut before the serve command was added to the command line.

so if you want to add a command to the path, you should add `~/.config/composer/vendor/bin/` because daux is automatically symlinked there.

**Comment by absolutejam** [comment]
So, I spun up a fresh Ubuntu VM to make sure there's no pollution. After apt-get update/upgrade, I installed composer (`apt-get install -y composer`), then ran `composer global require justinwalsh/daux.io`

That throws the following:
![image](https://cloud.githubusercontent.com/assets/6817942/17346059/fd1c7e80-5900-11e6-9d16-6f3a6226d85a.png)

So, I installed php-mbstring (`apt-get install -y php-mbstring`) and the 'zip' package and re-ran the install command. Everything installed fine, but I only have `~/.config/composer/vendor/bin/commonmark` in that folder, I also tried `~/.config/composer/vendor/justinwalsh/daux.io/bin` but the only thing in there is 'compile'.

Thanks for your help and speedy reply!

**Comment by onigoetz** [comment]
Oh I get it, sorry that's my mistake.

By default composer installs versions that have a number, and I completely forgot that I pushed a '0.1.0' tag

I just pushed a '0.2.0' so a `composer global update` should do the trick.

My pleasure for the reply, I was working to fix a few issues on Daux.io tonight :D

**Comment by absolutejam** [comment]
I reverted back to an earlier snapshot of the VM and installed from fresh. Now I have the daux command and I have added the bin folder to my $PATH.

I've created a 'docs' folder and added in a test.md with some dummy content to begin with, but when I run `daux` or `daux --serve`, I get the following errors:

![image](https://cloud.githubusercontent.com/assets/6817942/17367104/78342ab6-5986-11e6-8120-2b5c22c1b978.png)

Sorry to be a pain!

**Comment by onigoetz** [comment]
hey no problem :D 

this is very weird, `utf8_encode` is a function that should be in the code of PHP, but it seems that in the latest versions it was moved to the `xml` extension (http://stackoverflow.com/questions/35701730/utf8-endecode-removed-from-php7)

Try a `sudo apt-get install php7.0-xml` on your machine, this should fix the issue.

Normally, the command is `daux generate` or `daux serve`.

`daux --serve` was a short lived experiment

**Comment by absolutejam** [comment]
Nearly there!

Installing php7.0-xml helped, and if I `daux serve --host 192.168.0.101` it hosts, but once I try to connect from another client, I get an Error 500 and a stack trace on the VM:

![image](https://cloud.githubusercontent.com/assets/6817942/17381435/ce95c2c4-59c3-11e6-9b47-369113f45ddb.png)

Thanks for your continued help :smile:

**Comment by onigoetz** [comment]
Okay, This means that there is no page found in your documentation, try to create at least one file named `index.md` and another page that will be the entry point to your documentation (like `getting_started.md`)

You need at least two files to get started

**Comment by absolutejam** [comment]
Awesome, added in an index.md and we're up and running!

Thanks for your help :)
