### ISSUE TITLE
Hard to understand how to mike Custom Theme

### ISSUE THREAD

**Issue by soulfly** [justinwalsh/daux.io#393]
It's really hard to understand what we need to do to build our own custom theme

> To use a custom theme, just copy over the theme folder as well as the .thm file for that theme into the themes directory and set its value in the theme param in config.json

Q1:
What is **themes** directory? Is it inside my documentation folder, near **docs** folder?

Q2:
What is **.thm** file? I didn't find anything about it in your doc and your repo

**Comment by onigoetz** [comment]
Okay, this seems to be a legacy documentation from a long time ago, I will update this.

I created a nicer documentation on creating themes here : http://daux.io/For_Developers/Creating_a_Theme

**Comment by soulfly** [comment]
Yes, I also checked that guide. But the main question is where to store all these files. It also not covered on that page.

**Comment by soulfly** [comment]
composer global require justinwalsh/daux.io

**Comment by onigoetz** [comment]
okay then for the moment you have to add your theme to ~/.composer/vendor/justinwalsh/daux.io/themes/yourtheme`

I will come up with a cleaner solution soon, but it's not an easy thing to do because of the `serve` command that needs everything in one place

**Comment by soulfly** [comment]
Thank you

**Comment by onigoetz** [comment]
Moved this to issue #396
