### ISSUE TITLE
Make it possible to use custom themes 

### ISSUE THREAD

**Issue by onigoetz** [justinwalsh/daux.io#396]
Custom themes can't be used with the `daux` command currently.

**Comment by onigoetz** [comment]
This will avoid the use of the workaround proposed in issue #393

**Comment by Mark-H** [comment]
I've started a $25 bounty to this as I'm also running into it. :) https://www.bountysource.com/issues/36898889-make-it-possible-to-use-custom-themes

**Comment by Mark-H** [comment]
I've tried the workaround in #393 (placing theme files in ~/composer/), however when I updated from 0.2.1 to 0.2.2 (as I noticed some things were newer than my own version) that wiped out my custom theme files. Durr. Luckily I still had them open in my IDE so no work lost, but that's a good reason to not store theme files there :P

**Comment by onigoetz** [comment]
Hello, 

I will have a look into it this week. this shouldn't be too complicated to implement, it just involves a bit of routing in the `serve` part.

**Comment by mateusmedeiros** [comment]
@onigoetz Would it be possible to also use custom templates with the same solution?

**Comment by Mark-H** [comment]
Will gladly double my bounty if it's done this week, as that would be perfectly timed for my project :) Let me know if there's anything I can do to help on this. 

(It probably doesn't make much of a difference, but I'm not use the `serve` command, just generating the static site and serving that.)

**Comment by onigoetz** [comment]
@mateusmedeiros yes it is specifically for custom themes, the default theme work out of the box with the global installation.

@Mark-H good to know, but I prefer to deliver features for all formats, if I don't it will become very complicated to understand what feature is available in what format

**Comment by mateusmedeiros** [comment]
@onigoetz But what I meant was, would it be possible to override [these templates](https://github.com/justinwalsh/daux.io/tree/master/templates) with the same solution?

Of course that would depend on how you implement it, but I guess it can't hurt to ask :grin:

**Comment by onigoetz** [comment]
Themes already allow to override these templates, it's explained here if you want to do it : http://daux.io/For_Developers/Creating_a_Theme#page_Overriding_templates

**Comment by mateusmedeiros** [comment]
Oh, my bad! I was only reading the README.md of the repo, I didn't know one could do that directly with the themes.

Guess I should've read the documentation on the website ):


Thanks for your help!

**Comment by onigoetz** [comment]
No problem, Daux has many features I myself forget about some sometimes ;-)

**Comment by onigoetz** [comment]
@Mark-H If you want to try it out already, I pushed changes to the `development` branch that allow you to work with custom themes.

To use it, you have to create a `themes` directory next to your `docs` directory (or you can change the  `themes_directory` option in your `config.json`)

The structure inside this directory is exactly the same as for the `themes` directory inside `daux` ( `themes/your-theme/config.json` )

@mateusmedeiros I tested and it works fine with custom templates in this case as well.

I will try to implement this feature for `serve` tomorrow.

**Comment by Mark-H** [comment]
Thanks @onigoetz! I'll try it out tonight or tomorrow :)

**Comment by Mark-H** [comment]
Looks like it's working perfectly @onigoetz - thanks! 

(If others are wondering how to install the development branch, try this: `composer global require justinwalsh/daux.io:dev-development`)

**Comment by Mark-H** [comment]
As promised I've doubled the bounty for this issue to $50 as you got it sorted right on time for the project I'm working on :D Make sure to claim it via https://www.bountysource.com/issues/36898889-make-it-possible-to-use-custom-themes

**Comment by onigoetz** [comment]
Thank you very much Mark. I also pushed fixes for the live serve feature so everybody can benefit from it :D
