### ISSUE TITLE
Provide folder-level configuration

### ISSUE THREAD

**Issue by onigoetz** [justinwalsh/daux.io#397]
As requested in #377

We need a way to change a folder's name, maybe an optional `config.json` in the folder could do it.

**Comment by Mark-H** [comment]
In the case of an index file in a folder, it would be great if that could look at the front matter for the title? It's already using it in the `<title>` tag, but the title on the page (breadcrumbs) show the folder name instead of what is set as title.

**Comment by onigoetz** [comment]
Sure, I can check this out

**Comment by onigoetz** [comment]
I'm closing this issue as the Daux project has been moved to https://github.com/dauxio/daux.io

As for this specific issue, I will not add folder-specific configuration for the moment
