### ISSUE TITLE
Add "edit on Gihub" links to pages

### ISSUE THREAD

**Issue by obrienmd** [justinwalsh/daux.io#398]
One great option in RTD / mkdocs is the ability have a link for editing each page on Github (or Gitlab, in some cases, but that's far less important at this point) that points directly to editing the markdown file in Github's web UI. For opening editing to non-developers, this can be very useful.

**Comment by onigoetz** [comment]
Hello,
Thanks for the idea, I will see how that can be done with a minimum of configuration.

**Comment by onigoetz** [comment]
Do you have a documentation example that has this "Edit on github" link ?

**Comment by dkisselev** [comment]
Here's a project that uses RTD: http://docs.sylius.org/en/latest/book/requirements.html

Click v:latest in the leftnav to expand it, and there's an 'edit on gtihub' link there.

At a bare minimum, we can just add a config parameter to set the 'edit on _' link prefix and generate the rest of the url from the directory structure. I also suggest making the _ option customizable for those using GitLab/BitBucket (or parsing the configured domain out to auto-insert where the user will be editing.

I think Daux should develop some specific opinions about how to handle doc pages hosted in a repo and how to sync those changes down (perhaps with a console command or webhook endpoint), that way we can go full-circle and auto-deploy changes as PR's are submitted.

**Comment by onigoetz** [comment]
For the moment I added an option to set your basepath to your documentation and it will automatically create the links to edit from GitHub. This is available in the development branch

**Comment by obrienmd** [comment]
Thanks!
