### ISSUE TITLE
Guide how to build custom navigation

### ISSUE THREAD

**Issue by soulfly** [justinwalsh/daux.io#399]
Would be great to have a guide how to build custom navigation

here is a good hint inside **Format/HTML/Template.php** class, **buildNavigation** method
https://github.com/justinwalsh/daux.io/blob/master/libs/Format/HTML/Template.php#L107
and people can use it as a basis

but anyway, some people need custom navigation structure, would be great to have a good guide

**Comment by onigoetz** [comment]
Hello,

I agree this could need a guide. For the moment you can't extend this easily, so I guess it would need a bit of rewrite to be extensible

**Comment by soulfly** [comment]
At the moment we have an access to **$tree** variable inside php template and can reuse some of your logic, so it's possible to build custom navigation, but need some time to learn how it works

**Comment by Mark-H** [comment]
For my use case I wanted to get rid of the top-most directory, `en`. It needs to handle multilingual in the future, but we'll handle that out of the tree when that happens. Here's how I got that working in the `layout/05_page.php` template:

```` php
            <?php
            $rendertree = $tree;
            $path = '';

            if ($page['language'] !== '') {
                $rendertree = $tree->value[$page['language']];
                $path = $page['language'];
            }

            echo $this->get_navigation($rendertree['en'], 'en', isset($params['request']) ? $params['request'] : '', $base_page, $params['mode']);
            ?>
````

Basically just adding ['en'] to the first two parameters. Doing one or the other breaks the links.  

Now the next challenge I'm facing is hiding a specific level from the _tree navigation_, but keeping it _in the url_. Here's an example of the structure:

![screen shot 2016-09-12 at 10 34 34](https://cloud.githubusercontent.com/assets/312944/18429580/8a456f04-78d4-11e6-8aad-424b27196cda.png)

The `v1.x` folder is what I want to get out of the tree nav. Tried with a [custom processor](http://daux.io/For_Developers/Creating_a_Processor) but so far my attempts aren't working. I can loop over the $root->getEntries() and get to the Directory instances I want to "hide", but it's either getting rid of the url fragment as well, or it's seeing a bunch of broken links when generating. 

I'm starting to think this part might not be possible and perhaps I just need to get rid of the version-specific folders entirely?

**Comment by onigoetz** [comment]
Hello Mark,

normally, Multilanguage like you're trying to do is already handled at configuration level : http://daux.io/Features/Multilanguage

But for your `v1.x` folder, there is no way currently to remove it from the displayed tree.

The tree that Daux uses to represent the files mirrors the final content. so, (re)moving things from the tree will move them for the generation as well.

**Comment by gbaumgart** [comment]
same here, need to have different navigation and the entire output as single page app. 

I got the navigation part done but i don't know how to get the HTML content for each entry.  Do you know how to get it by chance ?

at the end i want to create a single JSON object, including navigation and content.... Then i could add better search facilities ala typeahead, etc...

**Comment by onigoetz** [comment]
I started to create an output format with a single file, but it's broken at the moment. I will write tests for it and make sure I dont break it in the future





On Thu, Oct 6, 2016 at 2:42 PM +0200, "gbaumgart" <notifications@github.com> wrote:












same here, need to have different navigation and the entire output as single page app. 



I got the navigation part done but i don't know how to get the HTML content for each entry.  Do you know how to get it by chance ?



at the end i want to create a single JSON object, including navigation and content.... Then i could add better search facilities ala typeahead, etc...

**Comment by gbaumgart** [comment]
nice, thanks for the heads up!

**Comment by gbaumgart** [comment]
how you plan this to work ? would prefer actually an RPC api, ie: daux/name?format=json . nothing fancy but at least getting around generate....for the sake of ´fast´

if you need a RPC stack, i can add my one in a fork or PR : https://github.com/gbaumgart/xamiro/tree/master/xapp/Rpc

thanks, and dont bother too much about this, i am getting there in one way or another. just digged a lot this days in your API and i think its pretty straight forward enough for me to get this done quick.

**Comment by onigoetz** [comment]
Hi,
this is a bit off topic.

The code is here currently :
https://github.com/justinwalsh/daux.io/tree/master/libs/Format/HTMLFile

it can be used with : `daux generate --format=html-file`

---
Stéphane Goetz
Développeur Web

http://www.onigoetz.ch

Mobile : +41 79/824.77.68
Mail : stephane.goetz@onigoetz.ch

**Comment by gbaumgart** [comment]
ok, i just figured its easier to write the whole thing in Nodejs. Having a service RPC API for Navigation and content rendering seems best to build easy to integrate single-page apps with no iframe mess.

**Comment by onigoetz** [comment]
I'm closing this issue as the Daux project has been moved to https://github.com/dauxio/daux.io
