### ISSUE TITLE
Github spice urls and references are not auto linking

### ISSUE THREAD

**Issue by justinwalsh** [justinwalsh/daux.io#4]
Reported by reddit user:

>The "Github spice" and what I assume are supposed to be LaTeX formatting don't work in your example: http://cl.ly/image/1Q0Q0n2t0O0Q

[Source](http://www.reddit.com/r/webdev/comments/1i6gbv/create_sexy_documentation_for_your_app_or_project/cb1vg57)

**Comment by onigoetz** [comment]
We are moving to CommonMark and github issue linking is not supported out of the box, however, now you can extend Daux.io with Processors, this is ready in the development branch and will be merged in master very soon
