### ISSUE TITLE
Keeping daux update without overwriting personal changes

### ISSUE THREAD

**Issue by nisaac2fly** [justinwalsh/daux.io#40]
What is the best way to keep my version of daux.io updated with the latest version from GitHub without git overwriting the changes I have make in the "docs" directory. When I do a git pull, git complains about wanting to overwrite my changes to the config.json file. Thanks.

**Comment by onigoetz** [comment]
The way daux is packaged changed to be a composer dependency, you don't need to download daux and all its files separately anymore.

You can run `composer global require justinwalsh/daux.io` and it will install daux globally, you can then use the `daux` command to generate your documentation

(Your $PATH must contain `~/.composer/vendor/bin` for it to work)
