### ISSUE TITLE
Compile code for theme development

### ISSUE THREAD

**Issue by tylerfoulkes** [justinwalsh/daux.io#400]
I am trying to update the daux theme for my dauxIO documentation, basically all I want to do is use the default daux theme but just change the colors. I run the following command to update and compile the less files
```js
gulp watch
```
I then edit the "theme-blue.less" file and just change some of the colors and everything looks like its working, Gulp seems to be running the appropriate tasks, but no css changes are made, I just get the same css. Is there another Gulp command I need to run?

**Comment by onigoetz** [comment]
Hello, no there is no other command to run, can you check if there is anything different in the destination file ?

**Comment by tylerfoulkes** [comment]
@onigoetz Silly mistake, I didn't realize that I had created a new theme and had not added the less resources to the gulpfile.js. I added them and they are working as they should now.
