### ISSUE TITLE
Document heading nav items

### ISSUE THREAD

**Issue by obrienmd** [justinwalsh/daux.io#402]
In testing daux.io, one item I've missed vs. mkdocs and readthedocs is nav items for headings within a given document page once that page is open.

Example from rtd - see the light gray items on the left under "Content Verification" that show when this page is open:
http://nwjs.readthedocs.io/en/latest/For%20Users/Advanced/Content%20Verification/

**Comment by onigoetz** [comment]
Hello, you're talking about the Table of contents ?

This feature is described [here](http://daux.io/Features/Table_of_contents)

Basically, you can either add `[TOC]` at any place in your page. Or you can add the `auto_toc` setting to your configuration to add a table of contents on each page automatically

**Comment by obrienmd** [comment]
Sorry, I should have been more clear - I meant embedded in the left-hand nav, a "children" of the currently selected nav item.

**Comment by onigoetz** [comment]
Oh right I see.

I guess we can have a similar feature. But not as a priority for the moment

**Comment by onigoetz** [comment]
Closing this issue as we move the project to an organization: https://github.com/dauxio/daux.io, the packagist package name is now [`daux/daux.io`](https://packagist.org/packages/daux/daux.io) and we even have a [Docker image](https://hub.docker.com/r/daux/daux.io/).

If you are still interested by that feature, please open a new issue in the organization and we'll look into it.
