### ISSUE TITLE
bootstrap classes gone?

### ISSUE THREAD

**Issue by gbaumgart** [justinwalsh/daux.io#403]
Hi,
i just tried your new changes. It seems you removed the bootstrap classes in /templates and switched to something entirely custom.

Is that on purpose or did I miss something ? The thing is that we can't use our bootstrap stock themes anymore in daux. 

thanks in advance,
greets

**Comment by gbaumgart** [comment]
well, just tried to keep my old /templates folder but it seems you do set different css classes somewhere in your code.

ok, never mind, we will have to switch to another documentation generator now. What a pity, we did quite some work to daux working for us.

**Comment by gbaumgart** [comment]
well, closing this. thanks again for sharing, it's a nice project. but yeah, if you can't integrate it via standard css frameworks, it's pretty much unsuited in larger infrastructures.

**Comment by onigoetz** [comment]
Hello,

The idea of moving away of bootstrap is because for the few components/features we use from bootstrap it's not really useful to use such a big css file. we went from 22KB to 5KB.

And for the class naming, I switched to BEM class naming, which is way cleaner and easier to understand and theme.

What exactly do you need from bootstrap ? maybe there is a common ground we can find.

**Comment by gbaumgart** [comment]
ah, i understand. we use pretty much all from bootstrap (alerts, tabs, popups, accordion). We use it all over the place: for our software it self, and the interactive examples (opens things in the surrounding IDE,...) as well Code documentation generated with JSDoc and PHPDoc variants. So the user has everywhere the same look and feel and custom version can get easily rebranded. 

anyway, i understand your point, I just figured i will stick with your older version and try to merge the new updates manually to keep it boostrap compatible (soon with the twbs SASS version which goes hand in hand with all our projects). 

g

**Comment by gbaumgart** [comment]
hi again,
do you know by chance when you removed support for boostrap ? I am trying to merge your fixes for the new link renderer in my fork which wants to stick to bootstrap,...

thanks

**Comment by onigoetz** [comment]
Hello,

almost all theme changes occured in this commit : 05a39eeeff60150c76011ce03972876d1d4e0041

**Comment by gbaumgart** [comment]
ah, didn't got the notification. At the end  I did end up with my own documentation tool, thanks to "showdown" and the stuff i already had: https://cloud.githubusercontent.com/assets/1205100/20343806/3cb7fcc6-abf0-11e6-92ea-43eb807a8eea.png

and here with own markdown editor: 
![image](https://cloud.githubusercontent.com/assets/1205100/20362375/a465752e-ac3b-11e6-9d63-da7ec6ea022c.png)

Possibly I can give you a pre-configured editor but also the "grid" for better navigation. let me know (its require-js, showdown ace and misc. = 1MB compressed JS)

going down with a custom impl. paid out well: no iframes, easy to embed in an application and more importantly: documentation can be interactive with the application (open sources, examples,...)

so, thanks again. daux gave me the right inspiration :-)
