### ISSUE TITLE
I need daux.io for multiple projects

### ISSUE THREAD

**Issue by tacnoman** [justinwalsh/daux.io#406]
Hello people.
I need daux.io for multiple projects in same source.
I'm developing this feature, Is interesting make a pull request for this?

I'm adding the flag `multiple_projects` in `global.json`.

``` json
{
    "docs_directory": "projects",
    "themes_directory": "themes",
    "multiple_projects": true, <= here
.......
```

The default will be false.

I'm adding the folder `projects` in root folder, and all folder inside this one will be a different project.

``` bash
├── projects
│   ├── project-1
│   └── project-2
```

And in URL, if the flag `multiple_projects` is equals `true`, the route in request URI will be in this format.
`
/<project_name>/<folder>/<subfolder>/<file>
`
If the flag is false, keep the current route.

This feature is interesting for this project?

**Comment by Mark-H** [comment]
I'm doing something similar, but my projects are simply the root directory level... in the theme it's just styled differently at the root of the nav tree. 

What would your feature make daux.io do differently?

**Comment by onigoetz** [comment]
Hello,

Like @Mark-H I'm not sure to understand what this feature will effectively do, can you explain a bit more please ?

**Comment by gbaumgart** [comment]
having pretty much the same problem, at the end you want to pass daux just another directory via url arg, same for the theme, likely relative to daux's root. right now you're forced to duplicate daux all over the place, per project and each with the possible themes. 
g

**Comment by onigoetz** [comment]
@gbaumgart That's exactly what I implemented last month with the globally installed daux.

Have a look here : http://daux.io/Getting_Started#page_Install

The new installation docs are up, after this command, you can use the `daux` global command to generate and serve your documentations from everywhere.

I hope this helps

**Comment by gbaumgart** [comment]
it does! thanks so much

**Comment by onigoetz** [comment]
Closing this as it's still unclear.
