### ISSUE TITLE
Allow absolute path in `--source`

### ISSUE THREAD

**Issue by Mark-H** [justinwalsh/daux.io#407]
Currently when passing an absolute path to the directory that holds the source documents, Daux is appending it to the current directory. 

Reason for wanting to pass an absolute path is that I'm triggering a rebuild via cron, and the paths are behaving differently there. On my local machine I'm simply passing `--source=.` as I don't have a separate /docs folder but via cron that's not working because the current directory is wrong.

**Comment by Mark-H** [comment]
After some code-diving I found the `DAUX_SOURCE` and `DAUX_THEME` environment variables. Been able of setting those on my cron job to point those two in the right direction.

`export DAUX_SOURCE="/home/user/docs.site.com/" && export DAUX_THEME="/home/user/docs.site.com/themes/" &&  ./build.sh`

(where `./build.sh` contains some code that runs `daux generate` as well as some other processing like creating a zip of the full docs for download)

However it looks like the destination doesn't have such a useful environment variable, so the files are placed in the wrong directory. Can probably figure a way around that tho.

**Comment by onigoetz** [comment]
Hello,
I added parameters to support absolute paths on source, configuration and themes.

destination was already an option you could set to an absolute path.

Everything is in the development branch.

**Comment by Mark-H** [comment]
Awesome, thanks :) Hopefully that'll help simplify my cron process a bit.
