### ISSUE TITLE
Missing themes directory

### ISSUE THREAD

**Issue by ksthar** [justinwalsh/daux.io#408]
I'm running:
- Nginx 1.10.1 
- PHP 5.6.24
- FreeBSD 10.3-RELEASE-p7

I am new to daux.io and this is my first installation.  I cloned daux.io again today (Sep-19-16) to have a fixed starting point, and when I access the main index page and the Getting Started page, they display as expected.  

However, when I click on a link in the navigation sidebar (e.g. "Auto Syntax Highlight" under "Features"), the page content loads, but the themes directory cannot be found so there is no CSS.  I verified there is no themes directory in the 01_Features directory.  I suspect the themes linkage is made dynamically somewhere in a script, but I'm not sure where this occurs.

In addition, I notice that when I click a "Features" item as above, the links in the newly loaded navigation sidebar now have an "extra" Features directory in their path, for example:

```
http://my.server.com/Features/Features/Auto_Syntax_Highlight
```

If I symlink the themes directory into 01_Features, the CSS is found, but the link artifact above is still created. 

Clearly, something isn't running correctly, and I suspect I'm not configured correctly.  However, I'm only seeing the 404's for the themes items in the logs, so I'm not sure where to probe next.  

Any help troubleshooting this installation would be most welcome!

Thanks,
HS

**Comment by onigoetz** [comment]
Hello,

I'm sorry I don't have the solution right away, I will need a bit more information to reproduce the case.

- I suppose you use the master branch, right ?
- Did you run a `composer install` after cloning the project ?
- Are you trying to serve daux from a sub-folder or at the root ?
- Can you please provide a copy of your nginx configuration ?

I hope I will be able to help you with these information.

**Comment by ksthar** [comment]
Thanks for the response.  I am using master and ran composer install.  Daux seems to work fine at the root level, it's at the sub-folder level where the issue occurs.

Full nginx.conf attached below:

    load_module /usr/local/libexec/nginx/ngx_mail_module.so;
    load_module /usr/local/libexec/nginx/ngx_stream_module.so;

    user www;
    worker_processes  2;

    events {
        worker_connections  1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        sendfile        on;
        keepalive_timeout  65;

        # HTTPS server
        #
        server {
    	    listen       80 default;
            listen       443 ssl;
            server_name  my.server.com;

            ssl_certificate      /etc/letsencrypt/live/my.server.com/fullchain.pem;
            ssl_certificate_key  /etc/letsencrypt/live/my.server.com/privkey.pem;

            ssl_session_timeout  5m;

	        ssl_ciphers 'ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256: DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384: ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA: DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA: DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA: AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA: AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5: !PSK:!RC4';

	        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	        ssl_session_cache  builtin:1000  shared:SSL:10m;

	        ssl_stapling on;
	        ssl_stapling_verify on;

	        ssl_prefer_server_ciphers on;
	        ssl_dhparam /etc/ssl/dhparam.pem;

	        add_header Strict-Transport-Security max-age=63072000;
	        add_header X-Frame-Options DENY;
	        add_header X-Content-Type-Options nosniff;

	        client_body_buffer_size 1K;
	        client_header_buffer_size 1k;
	        client_max_body_size 1k;
	        large_client_header_buffers 2 2k;
	        client_body_timeout 10;
	        client_header_timeout 10;
	        send_timeout 10;

	        charset utf-8;

	        root /home/ec2-user/daux;
	        index index.php index.html index.htm;

	        autoindex on;

	        if ($host !~ ^(my.server.com)$ ) {
	            return 444;
	        }
	        if ($request_method !~ ^(GET|HEAD)$ ) {
	            return 444;
	        }

	        location / {
		        if (!-e $request_filename){
		           rewrite ^(.*)$ /index.php$1;
		        }
		        auth_basic	"Authorization Required";
		        auth_basic_user_file /home/ec2-user/daux/.htpasswd;

		        try_files $uri $uri.html $uri.php $uri/ =404;
	        }


	          location ~ \.php {
		        fastcgi_split_path_info ^(.+\.php)(/.+)$;

		        root /home/ec2-user/daux;
		        fastcgi_pass unix:/var/run/php5-fpm.sock;
		        fastcgi_index index.php;

		        include fastcgi_params;
		        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		        fastcgi_param PATH_INFO $fastcgi_path_info;
	          }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                    root   /usr/local/www/nginx-dist;
            }

        } 

    }

**Comment by zeigerpuppy** [comment]
I am having the same issue, nginx config as recommended in #99 
I have also run composer install without errors.

The http://docs.example.com/Getting_Started shows fine
but subfolders can't find the theme files

eg: 
https://docs.example.com/Features/Auto_Syntax_Highlight

throws errors with finding theme files.
I think the theme folder URL is not getting re-written properly
```
Failed: GET https://docs.example.net/Features/themes/daux/js/jquery-1.11.3.min.js 
```

```
server {
    listen 80;
    server_name docs.example.com;

    index index.html index.php;
    charset utf-8;

    root /var/www/docs;

    location / {
        if (!-e $request_filename){
            rewrite ^(.*)$ /index.php$1;
        }
    }

    location ~ \.php {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param ENV production;
    }
}
```

**Comment by zeigerpuppy** [comment]
fixed by using the internal ./serve command and a reverse proxy
