### ISSUE TITLE
Destination doesn't work (always generated into static)

### ISSUE THREAD

**Issue by voycey** [justinwalsh/daux.io#409]
Hi Justin,

Thanks for creating this! I am having a bit of trouble generating the docs into a specific location:

`vendor/justinwalsh/daux.io/bin/daux --destination=notstatic`

Still generates the docs into `static`

I'm on PHP 7.0 Ubuntu 16.04

Thanks

**Comment by juliancesar** [comment]
+1

**Comment by onigoetz** [comment]
Hello,
this is a weird bug that comes from the default command.

because the `daux` command contains sub-commands (a la composer) and the default command is `generate`

But if the command is used with the default, parameters are ignored, I don't know why.

To make it work, use it this way : 

```
vendor/justinwalsh/daux.io/bin/daux generate --destination=notstatic
```

**Comment by onigoetz** [comment]
Hello again,

I had a look and fixed this in the development branch, you can have a look at it, it should work fine with your use case.
