### ISSUE TITLE
Themes documentation?

### ISSUE THREAD

**Issue by gbaumgart** [justinwalsh/daux.io#410]
Hi,
since you removed support for a well working and documented CSS framework and replaced it with something entirely custom, we're wondering you may have some more documentation? 

When looking in the new themes now,  its all looking awful named and it's obviously becoming hard to actually build something solid (documentation, extendable,....) on your CSS framework. 

it was sooo easy and good with bootstrap for us developers, and users building rich documentation, not any longer.... 

thanks,
g

**Comment by onigoetz** [comment]
Hello,
I think we've already discussed this.

the CSS in place now are based on BEM naming and this conversion was made because it's not needed for a documentation system to embed the full Bootstrap framework for only 5% of its features.

I will provide a documentation on how the theme is built and how to extend on it.

**Comment by gbaumgart** [comment]
I think I can live with the details of your commit, removing bootstrap support. At the end I need just to create custom theme which mirrors all bootstrap class declarations into your new CSS names. well, at least that's what i hope. I saw some things hard-coded somewhere in non customizable PHP code but I guess i get that covered as well. 

Problem with custom CSS frameworks is the absence of references, playgrounds and documentation. With Bootstrap it was easy because the internet is full of it. Very helpful for authors who write advanced docs,...

However, I gonna try loading bootstrap in top of a custom theme and hope to get away with that ;-)
thanks again for the heads up.
g
