### ISSUE TITLE
use offline fonts

### ISSUE THREAD

**Issue by xblox** [justinwalsh/daux.io#411]
Could you please include the robo font in the build. There lots of people don't even have internet and I know documentation needs to be often offline usable by heart. 
g

**Comment by mfilotto** [comment]
@xblox What about this issue ?
I would be very instrested to see this feature implemented as it is blocking for us

**Comment by onigoetz** [comment]
Hello,

doesn't it work with system fonts ?

**Comment by se0wtf** [comment]
Hi,
Same problem problem here as our daux doesn't have access to Internet.
The request to fonts.google.com stays in "Pending" and it's not usable.

Would be very nice to include the font in the build ;)

**Comment by mfilotto** [comment]
Hi,

Same here, it's definitly not working offline.
Could we re-open this issue ?

Any chance it would be implemented soon ?
We can not use Daux.io on our project because of this

**Comment by onigoetz** [comment]
Hello,

okay, I see it's something that's really wanted, I will look into it.

Just to keep my options open (I don't know the licences of the font and what they allow to do.) what would you prefer : 

1. Removing custom fonts and only keep a default font stack?
2. Embed the custom font ?

**Comment by mfilotto** [comment]
Hello,
Good new thanks :+1: 
I think the best would be to keep the same fonts (if licences allow to).
This way the change would have no impact on layout

**Comment by mfilotto** [comment]
For licence concern, [FAQ ](https://developers.google.com/fonts/faq) says :

> **Can I use fonts from the Google Fonts catalog on any page?**
_Yes. The open source fonts in the Google Fonts catalog are published under licenses that allow you to use them on any website, whether it’s commercial or personal._

**Comment by mfilotto** [comment]
To download the exact fonts I did this: 
- Go to https://fonts.google.com/?selection.family=Roboto+Slab:100,300,400,700
- Got to Customize panel
- Select Cyrillic - Cyrillic Extended
-  Click on Download button

![google-fonts](https://user-images.githubusercontent.com/9428574/29897822-75ec6d8a-8e2e-11e7-84d3-a1fa6eea05cb.png)

**Comment by mfilotto** [comment]
Another way to download fonts with included css : https://github.com/makovich/google-fonts-offline

**Comment by mfilotto** [comment]
@onigoetz Any progress on this one ?

**Comment by onigoetz** [comment]
Hello,

Thanks for the links, they were really useful. I just made those changes and made release 0.5.0.

By the way, the project has been moved to https://github.com/dauxio/daux.io, the packagist package name is now [`daux/daux.io`](https://packagist.org/packages/daux/daux.io) and we even have a [Docker image](https://hub.docker.com/r/daux/daux.io/)

**Comment by mfilotto** [comment]
It's working just fine
