### ISSUE TITLE
Edit On <Alternate Repository> Links

### ISSUE THREAD

**Issue by michaeltlombardi** [justinwalsh/daux.io#413]
Currently, we're able to include links in our documentation for editing on GitHub.

It'd be fantastic to have a similar option for editing on GitLab/BitBucket/VSTS.

**Comment by onigoetz** [comment]
Hello, I added a way to support your use case, you can use it with the following configuration:

```json
{
    "html": {
        "edit_on": {
            "name": "Bitbucket",
            "basepath": "https://bitbucket.org/onigoetz/daux.io/src/master/docs"
        }
    }
}
```

This is only available in the development branch for the moment.

**Comment by michaeltlombardi** [comment]
Perfect! Thank you! :)
