### ISSUE TITLE
"Call to a member function getUrl() on null" on generate

### ISSUE THREAD

**Issue by sirhopcount** [justinwalsh/daux.io#414]
Hi,

I'm trying to create some documentation with Daux but it keeps running intro an error when generating the documentation:

```
/srv # daux 
Copying Static assets ...                                                                                    [  OK  ]
Generating ...
- index.htmlPHP Fatal error:  Call to a member function getUrl() on null in /root/.composer/vendor/justinwalsh/daux.io/libs/Format/HTML/ContentPage.php on line 71
```

I installed Daux via composer:

```
# composer --version
Composer version 1.1.2 2016-05-31 19:48:11
```
Everything is running on php version:

```
php --version
PHP 5.6.26 (cli) (built: Sep 23 2016 14:47:01)
```

**Comment by onigoetz** [comment]
Hello, do you have at least two pages in your documentation ?

To start a new documentation you must have two pages : 
- index.md : The landing page
- *.md : Another page which is the first page of your documentation.

**Comment by sirhopcount** [comment]
That solves the problem (I just had an index.md). Thanks for for the help.
