### ISSUE TITLE
LinkNotFoundException in static generator

### ISSUE THREAD

**Issue by gbaumgart** [justinwalsh/daux.io#415]
Hi,
it throws an error when generating a static version. That shouldn't be because its the author's responsibility to have files in place or not.

There are scenarios where you'd like to have indeed pages removed for certain compilations of the docs.

thanks,
g

**Comment by onigoetz** [comment]
Hello,
LinkNotFound is an error that is thrown when you made a link to a page of documentation and it isn't found.

This error is a helper to not have dead links in your documentation

**Comment by gbaumgart** [comment]
yeah but its a decision you should leave to the authors. most doc generators are cool about this and crashing the whole build-chain ;-)
just saying, this behaviour makes little sense in reality.

**Comment by gbaumgart** [comment]
there are cases where you want remove on purpose pages !!

**Comment by gbaumgart** [comment]
never mind, fixed in my fork
