### ISSUE TITLE
Allow Mulitple Format Options in Config

### ISSUE THREAD

**Issue by matdave** [justinwalsh/daux.io#417]
Currently a Config can only allow one format, e.g. "html".  It would be awesome if we could output to both "html" and "html-file" through the config, so we could serve one as a _printable_ version.

**Comment by onigoetz** [comment]
Hello, the whole system is for the moment created to do one thing at a time. and the serve system is a second class citizen

So, given how the system works, I sadly can't tell you that this will happen anytime soon.

**Comment by onigoetz** [comment]
Closed for the moment as you can run the command two times, once with `--format=html` and once with `--format=html-file`
