### ISSUE TITLE
Docs - View Source link Missing Source content

### ISSUE THREAD

**Issue by NickStees** [justinwalsh/daux.io#418]
docs/01_Features/GitHub_Flavored_Markdown.md#images contains a link at the bottom to "view the source of this content" but it links to a different document, which is missing the markdown for images.

**Comment by onigoetz** [comment]
You're right, this link seems to be copied from somewhere else, I will fix this.

In the meantime, the page you're looking for is : https://github.com/justinwalsh/daux.io/blob/master/docs/01_Features/GitHub_Flavored_Markdown.md
