### ISSUE TITLE
Selecting a heading of similar name within the nav expands both groups

### ISSUE THREAD

**Issue by nathanb21** [justinwalsh/daux.io#420]
I have one Navbar header named `Experiment` and another named `Experiment Yield` - each of these contains sub-items, and neither has their own homepage (opening one will open the first sub-item).

If I open `Experiment` all is fine, but if I open `Experiment Yield` the page navigates to the page for the first sub-item and both groups are now expanded, rather than just the one I clicked. 

I am running the 0.2.3 install of Daux from Composer.

**Comment by onigoetz** [comment]
I will check this, this seems to be a bug

**Comment by onigoetz** [comment]
Hello, this is fixed in the development branch, you can test it with `composer require -g justinwalsh/daux-io:dev-development`
