### ISSUE TITLE
Auto-generated Table of Contents mixes header levels

### ISSUE THREAD

**Issue by wezzer** [justinwalsh/daux.io#421]
Hello,

Using the latest build, I just noticed that the automated Table of Contents (TOC) sometimes gets header levels wrong.

See for yourself by using the following markdown and note how second instance of "header 2" is actually shown on level 1 in TOC:

![screen shot 2016-11-15 at 15 38 59](https://cloud.githubusercontent.com/assets/12997174/20307786/bbe33774-ab49-11e6-8587-30743116dc0d.png)

```Table of Contents
[TOC]
# Header 1
## Header 2
### Header 3
## Header 2

**Comment by onigoetz** [comment]
I noticed this as well, I will have a look at it.

**Comment by onigoetz** [comment]
Hi, I fixed and pushed the changes to master, I will make a release in the next days

**Comment by wezzer** [comment]
Great, thank you very much!
