### ISSUE TITLE
Page specific meta description

### ISSUE THREAD

**Issue by Mark-H** [justinwalsh/daux.io#422]
Is there a way to add page specific meta description, perhaps through [front matter](http://daux.io/Features/Front_Matter)?

**Comment by Mark-H** [comment]
Found a way! In the markdown files:

````
---
title: 'Hello!'
description: 'Welcome to this awesome page.'
---
````

And in the layout/00_layout.php file of the theme:

    <?php
    $desc = $params->getCurrentPage()->getAttribute('description');
    if (!empty($desc)) {
        echo '<meta name="description" content="' . htmlentities($desc, ENT_QUOTES, 'UTF-8') . '" />';
    }
    else {
        echo '<meta name="description" content="The official documentation for modmore extras." />';
    }
    ?>

**Comment by onigoetz** [comment]
Exactly :D
