### ISSUE TITLE
Title link anchor could not support utf8 words

### ISSUE THREAD

**Issue by andares** [justinwalsh/daux.io#423]
bug example:

[https://github.com/andares/combi-docs/blob/master/static/Core_%E6%A1%86%E6%9E%B6%E5%9F%BA%E7%A1%80/Meta%E5%AF%B9%E8%B1%A1/Collection%E4%B8%8EStruct.html](https://github.com/andares/combi-docs/blob/master/static/Core_%E6%A1%86%E6%9E%B6%E5%9F%BA%E7%A1%80/Meta%E5%AF%B9%E8%B1%A1/Collection%E4%B8%8EStruct.html)

see line 72~142

it should be urlencode() and assign to anchor in link.

**Comment by onigoetz** [comment]
Hello,

Thanks for the report, I will have a look at this.

**Comment by onigoetz** [comment]
Hello, this is fixed in the development branch, you can test it with `composer require -g justinwalsh/daux-io:dev-development`
