### ISSUE TITLE
Where to add custom classes?

### ISSUE THREAD

**Issue by absolutejam** [justinwalsh/daux.io#424]
Hi,

I've tried adding a few custom classes or tweaks to existing ones, but the changes are never applied. Am I adding them to the wrong files (`/var/www/themes/daux/less/_typography` and `_utilities`) or do I need to manually clear any generated .css files?

Thanks!

**Comment by onigoetz** [comment]
Hello,

The theme files are built with gulp, you need the `package.json` and `gulpfile.json` at the root of the project to build the themes.
