### ISSUE TITLE
The directory link error

### ISSUE THREAD

**Issue by Jackielzq** [justinwalsh/daux.io#425]
![image](https://cloud.githubusercontent.com/assets/22285855/21169811/7bcaff6a-c1fa-11e6-8351-92de8982df50.png)
when clicking any link，it shows like this
![image](https://cloud.githubusercontent.com/assets/22285855/21169825/9c44cca8-c1fa-11e6-90b4-7aa17dbae3e1.png)
not what it should be ,  anyone who can help me solve this ,many thanks!

**Comment by onigoetz** [comment]
Hello,

Can you send me your settings and the command you use to start the server ?

**Comment by Jackielzq** [comment]
@onigoetz   Hi, I used the MAMP to start an apache server .  and change settings of httpd.conf file as the others said online.  when I download a former version of daux, nothing changed of setting , it worked, so I think maybe there is something wrong with the latest version,  when clicking the subdirectory and page files, it shows a strange page just like the second screenshot

**Comment by onigoetz** [comment]
Thank you for your answers, did you do a `composer install` after the download ?
If not that means you are using `daux.phar` which is an unsupported version (the previous way to package the applications)

**Comment by Jackielzq** [comment]
@onigoetz  Many thanks,   
not yet, I'm not familier with coding, I just download the zip file，unpacked it ，and use MAMP to serve it， do you mean if I do the composer install, this problem will be solved ? cause I am using the old version, and it seems OK right now
