### ISSUE TITLE
Error Loading Docs

### ISSUE THREAD

**Issue by alexcurtin** [justinwalsh/daux.io#426]
I am running a containerized version of daux and have an entry point script that adds a remote repository to the `/docs` folder at `/var/www/html/docs`. The Daux Index page I made loads fine but when I go to view any of the docs in the docs folder I get this error. Any ideas?

>Fatal error: Uncaught Error: Call to undefined method Todaymade\Daux\Config::getHTML() in /var/www/html/templates/content.php:12 Stack trace: #0 phar:///var/www/html/daux.phar/vendor/league/plates/src/Template/Template.php(118): include() #1 phar:///var/www/html/daux.phar/vendor/league/plates/src/Engine.php(277): League\Plates\Template\Template->render() #2 phar:///var/www/html/daux.phar/libs/Format/HTML/Template.php(53): League\Plates\Engine->render('theme::content', Array) #3 phar:///var/www/html/daux.phar/libs/Format/HTML/ContentPage.php(101): Todaymade\Daux\Format\HTML\Template->render('theme::content', Array) #4 phar:///var/www/html/daux.phar/libs/Format/Base/SimplePage.php(22): Todaymade\Daux\Format\HTML\ContentPage->generatePage() #5 phar:///var/www/html/daux.phar/libs/Server/Server.php(63): Todaymade\Daux\Format\Base\SimplePage->getContent() #6 /var/www/html/index.php(80): Todaymade\Daux\Server\Server::serve() #7 {main} thrown in /var/www/html/templates/content.php on line 12

**Comment by alexcurtin** [comment]
I downloaded this repo and ran the docker-compose up for both the php5 and php7 versions. I then tested loading the test docs that come w/ Daux and ran into the same error!

Getting Started

Wednesday, December 14, 2016 3:46 PM
Fatal error: Call to undefined method Todaymade\Daux\Config::getHTML() in /var/www/templates/content.php on line 12

Any ideas whats going on?

**Comment by onigoetz** [comment]
Hello, 
The `daux.phar` version is not recommended to use.

We will probably provide versionned `daux.phar` archives upon release. but not added to the repository. The problem is that it adds a lot of size to the repository and is cumbersome to update on each code change.

You should use it through `composer global install justinwalsh/daux.io`

**Comment by alexcurtin** [comment]
@onigoetz I am confused sorry. What is the solution to getting Daux to work inside Docker now?

**Comment by wezzer** [comment]
I'm wondering the same question: can we run Daux inside Docker anymore?

**Comment by onigoetz** [comment]
Hello, yes it's possible ton run daux inside docker. Either by creating an image that does a composer require justinwalsh/daux.io or by mounting the daux repository
I will probably create a docker image on docker hub to simplify that

Get Outlook for iOS




On Fri, Mar 3, 2017 at 11:36 AM +0100, "Antti Toivanen" <notifications@github.com> wrote:












I'm wondering the same question: can we run Daux inside Docker anymore?

**Comment by saintzyo** [comment]
Hi.
I have the same problem, bun not in Docker. I have a server with nginx and php-fpm. And sometimes one page can be opened without errors and sometimes a get an error "FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Todaymade\Daux\Config::getHTML() in..."
Can somebody help me?

**Comment by arvi** [comment]
Hello,

I am encountering the same issue with shared hosting:

```
Fatal error: Call to undefined method Todaymade\Daux\Config::getHTML() in [project_path_here]/documentation/templates/content.php on line 12
```

Version

```txt
PHP 5.6.29 (cli) (built: Dec  9 2016 23:39:41)
```

Modules
```txt
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
ereg
exif
filter
ftp
gd
gettext
hash
iconv
imagick
imap
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
pspell
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

It is working fine locally, but not when it's on remote server. Any tips to solve this? Thanks a lot.

**Comment by saintzyo** [comment]
@arvi just run `composer install` in root directory.
