### ISSUE TITLE
Integration with discourse

### ISSUE THREAD

**Issue by zeigerpuppy** [justinwalsh/daux.io#428]
I am trying to integrate daux with discourse commenting system (http://www.discourse.org).
I can get it to work with dynamic pages by putting this in `templates/content.php`

```php
	<!--Embed Discourse-->
	<div id='discourse-comments'></div>
	
	<script type="text/javascript">
	  DiscourseEmbed = { discourseUrl: 'https://forum.server.net/',
	                     discourseEmbedUrl: '<?= 'https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']; ?>' };
	
	  (function() {
	    var d = document.createElement('script'); d.type = 'text/javascript'; d.async = true;
	    d.src = DiscourseEmbed.discourseUrl + 'javascripts/embed.js';
	    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(d);
	  })();
	</script>
```

However, it doesn't work in static pages as the `$_SERVER['REQUEST_URI'];` returns empty.

I think I need to use something like this command to return the current URL instead:
```php
<?= $base_url . '/static' . $page['prev']->getUrl() ?>
```

Is there a similar command for the 'current' page, I can't seem to find one.
Sorry if it's an obvious question, I'm a bit new to PHP!

**Comment by onigoetz** [comment]
Hello,

no problem that's a good question, a bit of documentation to explain what variables can be used would be a welcome addition I think :D 

Here are the different variables passed to the template : https://github.com/justinwalsh/daux.io/blob/master/libs/Format/HTML/ContentPage.php#L75-L90

I guess you could try with `$relative_path` or `$path`

**Comment by zeigerpuppy** [comment]
thanks @onigoetz, I'll try that out

**Comment by zeigerpuppy** [comment]
OK, solved this, the variable to use is `request`
So I ended up using this code:

```php
<!--Embed Discourse-->
	<div id='discourse-comments'></div>
	
	<script type="text/javascript">
	  DiscourseEmbed = { discourseUrl: 'https://forum.server.net/',
	                     discourseEmbedUrl: '<?= 'https://myserver.net/static' . $page[`request`]; ?>' };
	
	  (function() {
	    var d = document.createElement('script'); d.type = 'text/javascript'; d.async = true;
	    d.src = DiscourseEmbed.discourseUrl + 'javascripts/embed.js';
	    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(d);
	  })();
	</script>
```

It works beautifully, each page gets it's own discussion and linkbacks from Discourse work properly.
