### ISSUE TITLE
Layout does not change

### ISSUE THREAD

**Issue by israelcueva** [justinwalsh/daux.io#429]
Hello

I have a DAUX installation, however, when I modify the `layout/00_layout.php` file and `layout/05_page.php` is not changed on the server.

The CSS styles and MDs if they change.

Thank you.

**Comment by onigoetz** [comment]
Hello,

How did you install daux and how are you using it ? 
( with `composer install justinwalsh/daux.io` or downloaded the repo and use `daux.phar` ?)

If you downloaded the repo and didn't do a `composer install` you're most probably using the `daux.phar` which means that `layout/*.php` files are compiled inside `daux.phar`

The solution is to run `composer install` in this case.

**Comment by onigoetz** [comment]
Closing for non-activity
