### ISSUE TITLE
Custom 404 page for static view

### ISSUE THREAD

**Issue by zeigerpuppy** [justinwalsh/daux.io#431]
I am trying to create a custom 404 page for the static site view.

If I direct 404 errors to the static root, then it serves the message from `Server.php`:
```php
throw new NotFoundException('The Page you requested is yet to be made. Try again later.');
```

However, this then directs users to links that are not static (they are effectively now out of the static root) and have lost the search bar.

Is it possible to create  a hidden page in the static view (that doesn't show in the Nav menu) that can be used as a 404 page?

**Comment by onigoetz** [comment]
Hello, yes I think we can generate a page for this.

**Comment by onigoetz** [comment]
I'm closing this issue as the Daux project has been moved to https://github.com/dauxio/daux.io

For this specific issue, I'll have a look to create it in the project
