### ISSUE TITLE
'daux' command does not understand -q option 

### ISSUE THREAD

**Issue by soulfly** [justinwalsh/daux.io#440]
`~/.composer/vendor/bin/daux -q `

returns error

```
[Todaymade\Daux\Exception]                                      
  The Docs directory does not exist. Check the path again : docs 
```

But I see this option when I request help:
`~/.composer/vendor/bin/daux -h`

**Comment by onigoetz** [comment]
Hello, I'm not sure to understand what result you wish to get ?

**Comment by soulfly** [comment]
When you use **~/.composer/vendor/bin/daux -q** then nothing should be returned according to help:

> -bash-4.2$ ~/.composer/vendor/bin/daux -h
> Usage:
>   generate [options]
> 
> Options:
>   -c, --configuration=CONFIGURATION  Configuration file
>   ...
>   -q, --quiet                        Do not output any message
> Help:
>   Generate documentation

**Comment by onigoetz** [comment]
I see, actually this is a parameter that comes by default with the symfony console for the moment I don't use it. maybe in the future. but it isn't planned yet.
