### ISSUE TITLE
TOC Doesn't support sub-lists properly

### ISSUE THREAD

**Issue by trevor-poppen-spreetail** [justinwalsh/daux.io#441]
The TOC is displaying, but it doesn't handle the following case:

```
# Top level

## Second Level

### Third Level

## Second Level

### Third Level
```

It displays the table of contents as the following:

- Top level
  - Second Level
    - Third Level
- Second Level
  - Third Level

Instead of what I would expect:

- Top level
  - Second Level
    - Third Level
  - Second Level (again)
    - Third Level (again)

**Comment by onigoetz** [comment]
Hello,

this issue was already reported in #421 and fixed in be6438a.

You are probably using daux through `daux.phar` try using `composer global require justinwalsh/daux.io` to use daux as a command line tool.
