### ISSUE TITLE
"daux generate" does not copy the daux theme into the static directory

### ISSUE THREAD

**Issue by mateusmedeiros** [justinwalsh/daux.io#442]
I'm using version 0.3.2, with a global installation from composer and a custom theme.

I have two directories in my project, `docs` and `themes`. The `themes` directory contains my custom theme.

When running `daux serve` in my computer, everything works great and I can see that the js files within the default theme (e.g. `http://localhost:8085/themes/daux/js/daux.js`) are served just fine, even though there's no `daux` directory inside my project's theme directory.

I may have misunderstood something, but if I understand correctly, I believe that's the best behavior because we are not supposed to clone the whole daux.io project inside our projects anymore (which is something that was supposed to be done before).

Now, if that's really the case, I was expecting to get the same results when deploying my project using `daux generate`, meaning having a `daux` theme inside `static/themes`. That doesn't currently happen, though, and as a consequence of that, I get some 404 errors on the browser console and the search function and the highlight function both don't work in my production environment.

**Comment by onigoetz** [comment]
Hello,

Just to summarize, you have a custom theme, and some files (from the daux theme) aren't found after running `daux generate`, right ?

Normally, when doing a static version, it copies only your current theme, so that means that the files you're referring to from your custom theme should be copied to your theme.

This is only the case for assets, not for default templates.

I hope this answers your question.

**Comment by mateusmedeiros** [comment]
@onigoetz Hello, thank you very much for your answer.

I was expecting to be able to easily use a custom theme without needing to also override templates, but lines like [this one](https://github.com/justinwalsh/daux.io/blob/aa4ad02b4681fbb1f75a333e07093c4a681ef262/templates/layout/00_layout.php#L64) refer directly to the default daux theme.

When I use `daux serve`, these files are served just fine, even though they don't come from my custom themes. But when I use `daux generate`, only my custom theme is copied, like you said.
Because of that, lines like the one I linked return 404 on my production server.

I could've overriden the default template `00_layout.php` just to make a version with those lines pointing to my custom theme instead of `daux`, but what I ended up doing was copying the `daux/js` directory to my `static/themes` directory (so I got `static/themes/daux/js` and my server could find the file in the path specified in the generated html files).

I thought it would be nice if it worked out-of-the-box just like with `daux serve`, without me having to go inside the original daux theme to get js files and without having to override any template. I'm not completely sure though if that can be worked from within the template or if it would be a good idea to copy the daux theme alongside the custom theme on `daux generate`.

**Comment by onigoetz** [comment]
Like you say, it might be a good idea to copy the default daux theme over. it's not that big and simplifies the creation of a custom theme.

**Comment by mateusmedeiros** [comment]
Yeah, that's what I thought. Thanks!

**Comment by eisbehr-** [comment]
When doing this, like on normal generation actually too, don't copy the `.less` files! They are not needed in the static folder. Just ignore them in all tasks ...

**Comment by onigoetz** [comment]
I'm closing this issue as the Daux project has been moved to https://github.com/dauxio/daux.io
