### ISSUE TITLE
Layout settings

### ISSUE THREAD

**Issue by 0dp** [justinwalsh/daux.io#445]
Hi There,

Is it possible to configure and lock the code block style so that users are unable to change the codeblock style ie. locked to Below?

Secondly, is it possible to enforce that the view is always two columns and never three? ie. currently the layout changes to two columns if there is no code blocks (and code block style is set to below)

Thanks for the great code

**Comment by onigoetz** [comment]
Hello,

yes, in your configuration, you can set `float` to false in the `html` section of your configuration : http://daux.io/Configuration/Html_export#page_Code_Floating
