### ISSUE TITLE
Fatal error, sometimes

### ISSUE THREAD

**Issue by frost2013** [justinwalsh/daux.io#448]
Hello!
I try to launch daux on several services: nginx, built-in php server (sudo ./serve), apache. Everything is ok, but sometimes pages, not index.php, wil crushed with error:

`PHP Fatal error:  Call to undefined method Todaymade\Daux\Config::getHTML() in /home/www-data/apps/daux/templates/content.php on line 12`

I thought, that this is low memory to work PHP. I increment to 512 MB, but problem still exists.
Configuration for nginx:
```
server{
    #имя сервера:
    listen 192.168.1.225:8085;
    server_name wiki.ru;

    #логи
    access_log /var/log/nginx/wiki.access.log;
    error_log  /var/log/nginx/wiki.error.log;

    # корневая директория
    root /home/www-data/apps/daux;
    
    # setup base features
    index index.php index.html;
    charset utf-8;

    location / {
        if (!-e $request_filename){
            rewrite ^(.*)$ /index.php$1;
        }
    }

    location ~ \.php {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        #fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_pass localhost:9001;
        fastcgi_index index.php;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

}
```

I'm not install composer and another programs, only nginx, php-fpm, php-cgi.
I edit nginx site configuration with to ways: fastcgi_pass *.sock and pastcgi_pass IP:Port. Both of them are work bad.
Please, help! :)

**Comment by frost2013** [comment]
Any ideas ?

**Comment by frost2013** [comment]
I found solution.
The error is occurs, if not exists folder "vendor", which created by composer. The engine use PHAR file and the error is occur.
If I execute command "composer install" and folder "vendor" create, the error is down.
Thank you!
I close issue.

**Comment by onigoetz** [comment]
Hello, thanks for the info, I'll have a look into why this happens.

Though I don't recommend to use the .phar, a composer install is more maintainable

**Comment by miaulightouch** [comment]
if I don't read this issue, I still can't get my site work.
