### ISSUE TITLE
Fatal error: Unable to find Gruntfile.

### ISSUE THREAD

**Issue by tatoosh** [justinwalsh/daux.io#449]
I can't get daux.io running on my windows 10.
The grunt command always have an error: Fatal error: Unable to find Gruntfile.

Where to get the gruntfile from or is there a better solution for a windows user?
Thx Tatoosh

**Comment by onigoetz** [comment]
Hello, the Gruntfile was removed, we use Gulp tu build the styles now.

However you might not need either if your goal is just to serve or generate documentation.

http://daux.io/Getting_Started#page_Getting_Started

You can see here how to install Daux and use the `daux` command line.
