### ISSUE TITLE
Move to an organization

### ISSUE THREAD

**Issue by onigoetz** [justinwalsh/daux.io#452]
Hi @justinwalsh,

I tried to contact you about this but got no answer from you. 

Can we move daux.io to an organization ?
I created one and invited you to it : https://github.com/dauxio

Also, the development/production sites don't update anymore on push.
Is it possible for me to take the domain and move the site to my servers ?

Thanks in advance

**Comment by eisbehr-** [comment]
As @justinwalsh isn't here anymore, it would be nice imo! There are some things that should be fixed. And it would be nice, if more than one person could do this. Like fixing the doc update, adding services to repo, and have real access. So, thumbs up from me for an organisation!

**Comment by eisbehr-** [comment]
Interesting that @justinwalsh has made commits in the past days, but seems to don't like to make any reply here or somewhere else on the project.

@onigoetz How about to deprecate that repo (replace the readme with a deprecated info and remove the files from master) here and move a fork to the oganization by yourself? I know, it's kind of a break, but I think that will be the only way forward now.

**Comment by LazyKnightX** [comment]
If the owner don't update this, it's good to move this project.
This is a great document framework deserve continuing.

**Comment by onigoetz** [comment]
I agree with you @eisbehr- and @LazyKnightX I already created the organization and gave access to @justinwalsh to move the repo to it.

The thing if I just fork/copy the repo, it won't keep the stars and forks, and it's a bit sad.

**Comment by eisbehr-** [comment]
But when @justinwalsh has no interest anymore and not even post a single comment here, the project will die soon or later, with stares or not. 😢

**Comment by onigoetz** [comment]
I agree, but In the meantime I have full commit access, so at least I can contribute :)
I will check with Github if there is something they can do

**Comment by eisbehr-** [comment]
Maybe we should write @justinwalsh via [linkedin](https://www.linkedin.com/in/justindwalsh/). 😉

**Comment by onigoetz** [comment]
Well, I already did :) on Twitter as well, both in private message and public

**Comment by mateusmedeiros** [comment]
@onigoetz The issue with the stars, PRs, issues, forks (and anything else not directly tied to the git repo) not transferring is exactly the reason I've been reluctant to give this suggestion before. But since I've been watching this repo, I have definitely seen a lot of effort on your side to contact @justinwalsh on issues and etc, all to no avail (and all the while we see him active on private repositories).

If github were willing to transfer the ownership without direct authorization of @justinwalsh (maybe making it reversible for some time if he wants or something like this) it would be the ideal solution, but if that turns out to not be possible at all, and if he keeps ignoring this project, maybe it would really be better to just push the git repo on the new repo on @dauxio / fork it there. Desperate times call for desperate measures, I guess. 😔

**Comment by onigoetz** [comment]
@mateusmedeiros I contacted Github yesterday on this issue with this exact request :) 

I agree with you, if Github comes with a negative answer, I will just push the repo to the organization and change the pages here to explain that it's moved to an organization.

**Comment by eisbehr-** [comment]
Not only change the docs, even delete the complete files here. Just to be sure everyone noticed. The files are not lost, then just a commit behind. So nothing is lost. But I think that would make it clearer to people ...

**Comment by mateusmedeiros** [comment]
With a quick search I found a couple of tools that (apparently) can be used to copy the issues from this repo to the new one, if need be:
 * https://github.com/google/github-issue-mover
 * https://github.com/IQAndreas/github-issues-import

Sadly I don't see how we would be able to copy stars or forks or anything else ):

**Comment by onigoetz** [comment]
Hi, I created a separate project in an organization : https://github.com/dauxio/daux.io

I will also look into moving the current issues, or maybe closing them except for bugs, so we can know if the interest is still here for some features.

**Comment by eisbehr-** [comment]
Great! Looking forward to it! ;)

**Comment by eisbehr-** [comment]
In addition to the move: https://github.com/justinwalsh/daux.io/pull/474
