### ISSUE TITLE
Your config description and examples are quite unspecific

### ISSUE THREAD

**Issue by eisbehr-** [justinwalsh/daux.io#453]
As a new user to `daux.io` it is pretty hard to find out, what config parameter are available and where to place them.

At first, there is no overview anywhere, what parameters are available with a short description. You have to search all of them here on GitHub or in the documentation on many different sites. A small table would give users an overview what is possible.

On the other hand, the examples given in your documentation here on GitHub or on the official docs is very unspecific too. For example:

You always say _"place it into config.json in docs folder"_ and give such example code:
```JS
{
	"links": {
		"GitHub Repo": "https://github.com/justinwalsh/daux.io"
	}
}
```

But what you don't tell your users it, that this for example needs to be placed inside the `html` block of the config. So the example should be looked like this:
```JS
{
	"html": {
		"links": {
			"GitHub Repo": "https://github.com/justinwalsh/daux.io"
		}
    	}
}
```

It is even more confusing, because some examples have the `html` block included, as the rest don't have this. For example, `inherit_index` is documented with the `html` block:

```JS
{
        "html": {
        	"inherit_index": true
        }
}
```

It tooke me quite a lot time now to figure out, where to place my configurations to let them take effect. The documentation of the capabilities could be much better imo.

---

Antoher small hint on your documentation and files:

Nearly all your `json` files use a different intend. Your examples uses a `tap`, your `composer.json` uses four spaces, your `package.json` uses two spaces, and so on. The mostly used type out there is to use two spaces, like you did in your `package.json` already. This is better readable too, imo. Maybe use a default type of intention here.

As taken from the example above:

```JS
{
  "html": {
    "links": {
      "GitHub Repo": "https://github.com/justinwalsh/daux.io"
    }
  }
}
```

**Comment by onigoetz** [comment]
Hello,

thanks for the pointer, I didn't see the one in the README, I fixed it.
 
I also changed the indents on all documentation pages, you're right it's better when it's uniform.

Just in case, you can find all configuration options on these two documentation pages
- http://daux.io/Configuration/index
- http://daux.io/Configuration/Html_export

**Comment by eisbehr-** [comment]
Not completly. For example, the `html export` page is missing at least `auto_toc`, `auto_landing`, `inherit_index` and `search`. Thats what I mean when I said that it's needed to look everywhere for a complete set of options. And the other page is missing some options too ...

The readme looks great now! I think it's an real improvement here. You only misses two examples:
https://github.com/justinwalsh/daux.io#landing-page
https://github.com/justinwalsh/daux.io#title

And since yesterday, there should be an example added for `jump_buttons` too. 😉

**Comment by onigoetz** [comment]
You're right, some options are scattered around pages.
I grouped them all in the page, though it can't be seen on the website (Publishing is broken: #452)

They can be checked out here :
- https://github.com/justinwalsh/daux.io/blob/master/docs/05_Configuration/_index.md
- https://github.com/justinwalsh/daux.io/blob/master/docs/05_Configuration/Html_export.md

**Comment by eisbehr-** [comment]
Great! Thats better now!
