### ISSUE TITLE
Add an option to hide 'previous' and 'next' buttons

### ISSUE THREAD

**Issue by eisbehr-** [justinwalsh/daux.io#454]
It would be nice if there would be any config option to hide the `previous` and `next` buttons in the html output. I really don't like to have this buttons, but the only way seems to be a custom template. But I would like to work with the default theme, to keep it working on updates of `daux.io`.

For example:

```JS
{
  "html": {
    "jump_buttons": false
  }
}
```

Thank you!

**Comment by onigoetz** [comment]
Good for me :)

**Comment by eisbehr-** [comment]
Thank you!

**Comment by eisbehr-** [comment]
Is there a plan, when you will create a new release, so I could install this feature directly with composer?

**Comment by onigoetz** [comment]
I will try to make the release before the end of the week, in the meantime, you can directly install the master branch with composer with `composer require justinwalsh/daux.io dev-master` (with or without global, depends on how you install it)

**Comment by eisbehr-** [comment]
Sounds great, I can wait until then! Thanks! ;)
