### ISSUE TITLE
Wrong links in readme

### ISSUE THREAD

**Issue by eisbehr-** [justinwalsh/daux.io#457]
The badges in the `readme.md` are linked to `onigoetz/daux.io` instead of the original repo. I think thats the reason because they show wrong values ...

```TEXT
[![Latest Version](https://img.shields.io/github/release/onigoetz/daux.io.svg?style=flat-square)](https://github.com/onigoetz/daux.io/releases)
[![Software License](https://img.shields.io/badge/license-MIT-brightgreen.svg?style=flat-square)](https://github.com/onigoetz/daux.io/blob/master/LICENSE.md)
[![Build Status](https://img.shields.io/travis/onigoetz/daux.io/master.svg?style=flat-square)](https://travis-ci.org/onigoetz/daux.io)
[![Coverage Status](https://img.shields.io/scrutinizer/coverage/g/onigoetz/daux.io.svg?style=flat-square)](https://scrutinizer-ci.com/g/onigoetz/daux.io/code-structure)
[![Quality Score](https://img.shields.io/scrutinizer/g/onigoetz/daux.io.svg?style=flat-square)](https://scrutinizer-ci.com/g/onigoetz/daux.io)
[![Total Downloads](https://img.shields.io/packagist/dt/justinwalsh/daux.io.svg?style=flat-square)](https://packagist.org/packages/justinwalsh/daux.io)
```

**Comment by onigoetz** [comment]
Hello, it's because I don't have access to enable things like scrutinizer and travis on this repo. so I did it on my own fork.

That's why I asked the owner of this repository @justinwalsh if we can move the repository in an organization.

In the meantime, I will reset some of the links to the main repo.

**Comment by eisbehr-** [comment]
Is @justinwalsh still into this project? He seems to be not around here for a long time ...

**Comment by onigoetz** [comment]
He doesn't contribute anymore, that's why I suggested him we move daux to an organization and I will be able to fully manage the project
________________________________

**Comment by eisbehr-** [comment]
Yes, I had seen this. Would be recommend that too. ;)
Or at least give someone more rights ... There are some impacts actually, like you said.
