### ISSUE TITLE
Enhancement: GFM is missing task lists

### ISSUE THREAD

**Issue by eisbehr-** [justinwalsh/daux.io#460]
The GitHub flavored markdown is missing task lists, like this:

```TEXT
- [x] step one
- [x] step two
- [x] step three
- [ ] step four
- [ ] final
```

What results in the folowing:

- [x] step one
- [x] step two
- [x] step three
- [ ] step four
- [ ] final

**Comment by onigoetz** [comment]
Hello, yes, the statement that we support Github Flavored Markdown was made before GitHub introduced task lists.

After I started maintaining the project, the CommonMark specification came up and with it the CommonMark PHP implementation.

The great thing with it is that this implementation is extensible.
Meaning, If we find an extension that supports task lists I can include it and this feature will be available to you out of the box.

In the meantime, I could not find an extension that does it. So I will leave this task open as a feature request.

**Comment by onigoetz** [comment]
I'm closing this issue as the Daux project has been moved to https://github.com/dauxio/daux.io

I don't plan to add this feature soon
