### ISSUE TITLE
problems with page jump links, like in TOC, and special chars

### ISSUE THREAD

**Issue by eisbehr-** [justinwalsh/daux.io#461]
I've notices some problems with page jump links and special chars. For example, having a headline like this:

```TEXT
# TEST : Test
```

Will generate an `h1` element like this:
```TEXT
<h1 id="page_TEST+%3A+Test">TEST : Test</h1>
```

So the link, genereated by `TOC` is also escape the `:` chart to `%A3`:
```TEXT
#page_TEST+%3A+Test
```

But such jump links don't work with special char escaping. It should be used a generation like GitHub uses it. So the above example would result in `#test-test`, all lower case and separated by `-`, specialchars will be ignored completly.

**Comment by onigoetz** [comment]
Hello, I fixed this in the master branch, I didn't notice the escaped strings actually didn't work as URLS.

So I applied the escaping like you proposed, and I also added a uniqueness check in case two headings are identical
