### ISSUE TITLE
tipuesearch shows german umlauts wrong

### ISSUE THREAD

**Issue by 3qdev** [justinwalsh/daux.io#463]
german umlauts are not right showed in the search results, e.g. in the tipuesearch_content.json file is "f\u00c3\u00bcr" for "für" instead "f\u00fcr"

![screen](https://user-images.githubusercontent.com/21038186/27346655-1832b99c-55ee-11e7-972b-5e53aa40979e.png)

**Comment by onigoetz** [comment]
Ouch, my bad, will have a look into it, which OS and version of PHP are you using ?

**Comment by 3qdev** [comment]
I have tried Ubuntu 14.04 with HHVM 3.18.3 and Ubuntu 16.04 with PHP 7.0.18

**Comment by 3qdev** [comment]
Are there news about this issue, e.g. a work around?

**Comment by onigoetz** [comment]
Hi, just for information, this is fixed in https://github.com/dauxio/daux.io (in master branch for the moment)
