### ISSUE TITLE
Add footer to all pages via Processor

### ISSUE THREAD

**Issue by gamelaster** [justinwalsh/daux.io#464]
Hello, I want to add to every page custom footer. Is it possible via processor?
Thanks

**Comment by onigoetz** [comment]
Hello, sorry for the long response time.

It's not possible directly, though you can walk all the tree and for each content do `
`$node->setContent($node->getContent() . $footer)`

**Comment by onigoetz** [comment]
Closing this issue as we move the project to an organization: https://github.com/dauxio/daux.io, the packagist package name is now [`daux/daux.io`](https://packagist.org/packages/daux/daux.io) and we even have a [Docker image](https://hub.docker.com/r/daux/daux.io/).

If you are still interested by that feature, please open a new issue in the organization and we'll look into it.
