### ISSUE TITLE
Daux.io Website is Down

### ISSUE THREAD

**Issue by VincEmond** [justinwalsh/daux.io#465]
Here is the error that I have when trying to access the website: 

This site can’t be reached
daux.io’s server DNS address could not be found.
Search Google for daux io
ERR_NAME_NOT_RESOLVED

**Comment by onigoetz** [comment]
Thanks for reporting this issue. 

Sadly I don't manage the website, @justinwalsh can you help with this ?

**Comment by Jako** [comment]
The domain seems to be expired according to whois.

**Comment by onigoetz** [comment]
It depends where you look : https://who.is/whois/daux.io

I tried to buy it to redeploy on my own servers but couldn't finalize it.

**Comment by VincEmond** [comment]
From what I have seen as well, the website is registered until 2018-06-10T19:38:34Z.

**Comment by Jako** [comment]
According to https://www.nic.io/whois-search.htm it has the following states:

```
Domain Status: clientHold https://icann.org/epp#clientHold
Domain Status: autoRenewPeriod https://icann.org/epp#autoRenewPeriod
```

So there must be something expired.

**Comment by onigoetz** [comment]
Hi all, 

We don't have any answer from @justinwalsh but I put the website in Github pages in the meantime : https://dauxio.github.io/

@justinwalsh Please answer us, many people now rely on your side project, and it's sad to see it in this state. I already told you, we can move the project over to a Github Org and I can take over its maintenance.

**Comment by mateusmedeiros** [comment]
It's sad to see that he does contribute on private repositories but he doesn't answer over here. Guess he must be really busy or something like that, as I find hard to believe he would ignore this project just for the heck of it.

In the meantime, website-wise, maybe the best course of action would be to put the website on something like http://dauxio.com and when http://daux.io become available again go back to it. Now that http://daux.io is down, it's easier to do that, since there won't be two websites online simultaneously.

**Comment by VincEmond** [comment]
The website that @onigoetz just provided seems to work just fine. It should be able to give people the documentation for a while without having to setup a local instance in order to access the documentation. Thanks a lot !

**Comment by VincEmond** [comment]
@onigoetz For the moment you should change the hyperlink in the project description and README.md.

**Comment by mateusmedeiros** [comment]
@VincEmond That's true, I actually have no idea what happened with my brain, haha. The one on github pages work just fine and I think the best course of action would be to change any mention of an official website to it.

**Comment by onigoetz** [comment]
I will update the README, but I don't have access to the repository's configuration to change the link.
________________________________

**Comment by VincEmond** [comment]
Pull request #468 .

**Comment by VincEmond** [comment]
Website is back, documentation must be changed back to normal. I'll make a PR about that.
