### ISSUE TITLE
theme and template specification

### ISSUE THREAD

**Issue by a11smiles** [justinwalsh/daux.io#466]
@justinwalsh I am designing a custom template and theme.

Since the website is down at the moment, how do I specify in the `config.json` the template and the theme I want to use?

Thanks!

**Comment by VincEmond** [comment]
The site has been reuploaded, please look at this page : https://dauxio.github.io/For_Developers/Creating_a_Theme.html

**Comment by a11smiles** [comment]
@VincEmond the documentation is incorrect. You'll notice that I have a pending pull request with the corrections.
