### ISSUE TITLE
Request: automatic conversion from a unc path to file://

### ISSUE THREAD

**Issue by SebastianMarotzki** [justinwalsh/daux.io#471]
Hello!

I like to put some documents to a local network share and it would be nice, if it's possible to insert a UNC path like this "\\server\Any Subfolder\Examples" and get a path like this "file://server/any%20subfolder/examples/".

I think it would be a useful feature for "local" documentations.

With best regards
Sebastian

**Comment by onigoetz** [comment]
Hi,

you can't really transform a UNC path from `\\server\...` to `file://server`, is it would need to be mounted. it would need to be changed to `smb://server/...` and at this stage, why not write it directly like this ? it works on any OS.

**Comment by SebastianMarotzki** [comment]
Hi,
i have tested it with smb:// and it does not seem to work with Chrome or Internet Explorer on Windows 10. And additional i can't find any informations about "smb://" instead of "file://". Why it's not possible to transform UNC to file://? It should be a normal path, like a simple URL to any other file.

I think it would be good, because "under windows" you can copy & paste the path and when you take a look at the Markdown-File, you can see at once if the file is hosted on a web server or not. 

best regards
Sebastian

**Comment by onigoetz** [comment]
oh, my bad, I checked any you're right `file://server/...` works fine.

I think this is quite specific and I'm not entirely sure if I wish to add this to Daux by default.

The easiest would be to write a processor to do that.

**Comment by onigoetz** [comment]
I'm closing this issue as the Daux project has been moved to https://github.com/dauxio/daux.io
