### ISSUE TITLE
Multi-language Support for Buttons & Search field

### ISSUE THREAD

**Issue by SylviaMoschner** [justinwalsh/daux.io#472]
Hi,
it would be nice if I could set the text of the "previous", "next" & "view documentation" buttons in the config of my html-export. Also the "Search..." placeholder.

**Comment by onigoetz** [comment]
Hello,

Yes, that's a good idea, as we move the project to an organization: https://github.com/dauxio/daux.io, can you please re-create the issue there ?

**Comment by onigoetz** [comment]
done in https://github.com/dauxio/daux.io
