### ISSUE TITLE
Simple custom css

### ISSUE THREAD

**Issue by sebRomeo** [justinwalsh/daux.io#473]
Hi,

thanks for such a great soft ;)

I may have misunderstood how creating a theme works, but it's impossible for me to create a theme or even add my own custom css without changing files in composer program folder (appdata...)

I have tried everything with config.json (theme_path...) but managed to do nothing..

How can I achieve that please ?

**Comment by onigoetz** [comment]
Hello,

you're welcome :)

To add new themes, you have to create a directory next to the `docs` directory named `themes` that will contain a directory with your theme's name and within that you can create your theme.

Then you can run the daux command with `daux generate --themes themes`
It should do the trick

By the way, the project has been moved to https://github.com/dauxio/daux.io, the packagist package name is now [`daux/daux.io`](https://packagist.org/packages/daux/daux.io) and we even have a [Docker image](https://hub.docker.com/r/daux/daux.io/)

**Comment by richard-313** [comment]
Hello,
I tried the command "daux generate --themes themes" but I get the warning " The "--themes" option does not exist. ".
So what can I do?
Actually I would like to add a css lib to the daux theme but it also doesnt work.

Thanks for help :)

**Comment by topkat** [comment]
Have you made sure that your folder is sibling of the docs folder (at the same level ?) and includes the right directory structure ?

**Comment by richard-313** [comment]
Thanks for reply! 
The following picture shows my tree:
![daux](https://user-images.githubusercontent.com/10269756/30806850-a3c2c006-a1f7-11e7-9680-ca6ef283edbd.png)

The "new_theme" is a copy of the daux theme folder.

**Comment by topkat** [comment]
Your theme is inside the docs folder but it should be sibling (the same parent folder for 'docs' and 'theme' folder !)

**Comment by richard-313** [comment]
@sebRomeo Thanks a lot! It works now.
