### ISSUE TITLE
Search bar breaks front page rendering in mobile Opera

### ISSUE THREAD

**Issue by seisatsu** [justinwalsh/daux.io#475]
The top portion of a generated documentation front page under the default theme is squeezed sideways by the search bar instead of being placed underneath as expected.

https://i.imgur.com/oTX9vpl.png

**Comment by onigoetz** [comment]
Hello,
the project has moved to https://github.com/dauxio/daux.io and https://dauxio.github.io/

Can you please check if the problem is still present in this version. and if it's still present open the issue there ?
