### ISSUE TITLE
New demo for your list

### ISSUE THREAD

**Issue by davidbackstein** [justinwalsh/daux.io#476]
We are using the great daux.io for our software documentation.
We are pleased, if you want to add us to your demo list at http://daux.io/Getting_Started

https://docs.pixolution.org

We did some adjustments to fit our needs:

-  We used the language feature to handle different product versions.
- The global search is version sensitive
- Custom theme to meet our CD
- Implemented a version chooser
- We added an alert to the documentation when product versions are available.

Cheers!

**Comment by onigoetz** [comment]
Cool, thanks for the link, I'll add it to the list.

But the repo moved to : https://github.com/dauxio/daux.io

I don't have the access to close this one, that's why it's still here.

**Comment by davidbackstein** [comment]
Great!
Yes I am aware of the repo change. Good thing is this issue does not spam the real repo ;-)

**Comment by onigoetz** [comment]
oh no, it's not spam :) I'm happy to add examples to the list :)

BTW, it's added
