### ISSUE TITLE
Embedded HTML width

### ISSUE THREAD

**Issue by eric-burel** [justinwalsh/daux.io#478]
Hi,

I am tweaking Daux to build a course, and it is amazing. I am trying to embed HTML. However, width is always 100% even in sliced mode (menu on the left, text on the center, code on the left).

The embeded HTML takes all the space available. Here is a sceenshot :
![fiddle](https://user-images.githubusercontent.com/7983005/35163261-6dbc6ad4-fd46-11e7-84c5-f443195e3073.png)
Here, I thought the Fiddle would be only in the center column.
I am not sure whether this looks good or bad yet (the more I look at it the better it is^^), but anyway is this the expected behaviour ?

**Comment by onigoetz** [comment]
I'm closing this issue as the Daux project has been moved to https://github.com/dauxio/daux.io

If this is still an issue for you on the new project, please open an issue on the new repository.
