### ISSUE TITLE
Install on an VPS ubuntu or debian via Nginx

### ISSUE THREAD

**Issue by SofianeBoumedine** [justinwalsh/daux.io#479]
I don't understand with the documentation how install daux.io and deploy via nginx
Can I have some help about that?

**Comment by SofianeBoumedine** [comment]
up

**Comment by onigoetz** [comment]
I'm closing this issue as the Daux project has been moved to https://github.com/dauxio/daux.io

For your specific question, I would not recommend deploying the dynamic version, I recommend you generate the documentation in a build step and upload the static html files.
