### ISSUE TITLE
Can page title more friendly?

### ISSUE THREAD

**Issue by htynkn** [justinwalsh/daux.io#53]
When we visit every web page generated by Daux.io,the title of web page is always the same.

Maybe we can get more friendly title for each page,for example:
use Getting Started--DAUX.IO not DAUX.IO for the page:http://daux.io/Getting_Started

And just a idea,is there a plan to make daux.io to support other language,such as Simplified Chinese and Japanese?

Thanks~☺

**Comment by makailol** [comment]
Hello,

Sorry to write here on this closed task. I just would like to know whether daux.io has support to use different title for each page?

It would be nice to have support for meta description and meta keyword for each of the separate page.

Would you just confirm if this feature is already implemented in daux.io?

Thanks

**Comment by onigoetz** [comment]
Hello,
We intend to support metadata for the markdown format, this is discussed in #210 

Some of the meta informations could be used to generate the page
