### ISSUE TITLE
Create a grunt task to build a static set of the docs.

### ISSUE THREAD

**Issue by justinwalsh** [justinwalsh/daux.io#6]
This would be useful if you wanted to deploy to S3, Github Pages, or any static file server.

From reddit user:

> This project looked very appealing to me, until I read this part. I am not interested in a service like DocumentUp, I just want to be able to put the generated documentation on our CDN or S3, on our domain. We also have the need for internal docs that we don't want on any public server.
> I think the solution to this is to add support for optional, purely static export. An external, hosted documentation service will not fit our needs.

**Comment by prescottprue** [comment]
+1 for the Grunt task. It would be great to be able to throw this task into existing projects that have grunt by just having one package to install.
