### ISSUE TITLE
Problems with special characters in a filename

### ISSUE THREAD

**Issue by ghost** [justinwalsh/daux.io#66]
Hi, great web app.

When I use spanish special characters in the filename (like ñ, á, é, í, ...), the app show the file and the characters correctly in the left panel. But when I click the file it dosn't open them.

Example:
- filename `00_Administración`
- url `http://localhost/Administración` show:

```
Oh No. That page dosn't exist
```

**Comment by jirsbek** [comment]
Hello, thank you for great app, unfortunately I've got the same problem as isidrorg and klepas mentioned.

My fist MD file is called in Czech "00_O_nás.md" (About us). "á" character causes page not found. Testing on localhost (MAMP) as well as in built-in grunt-php.
