### ISSUE TITLE
Only prints 1st page in Firefox/Safari

### ISSUE THREAD

**Issue by susanBuck** [justinwalsh/daux.io#77]
Prints fine in Chrome, but will only print first page in Mac Firefox/Safari (Windows untested).

**Comment by georgesofroniou** [comment]
Hi, just wondering whether there is any update regarding this. I realised that if you specifically edit the css/less width then you can make it not be restricted to the initial column width. However I have not had any luck into understanding why it only prints one page of a document (Safari/Firefox on Mac)

**Comment by dkisselev** [comment]
@georgesofroniou Unfortunately daux isn't really actively maintained anymore, so no real updates to any of these older issues.
