### ISSUE TITLE
Next / Previous Page Capabilities

### ISSUE THREAD

**Issue by geebru** [justinwalsh/daux.io#93]
I'm currently using Daux for our company code manual and have it working pretty much perfectly.

I've moved onto making it mobile friendly and realized it would be really nice if there were an easy way to go to the "next" / "previous" page at the end of the doc.

This is more of a "help me" question than a bug or feature as I'm sure this is possible but can't find any documentation as to how to do it. I know I could hard-code the links but would prefer a more automatic solution.

**Comment by onigoetz** [comment]
Added in the development branch. Though I don't know if you still need it ;-)
