### ISSUE TITLE
Rewrite documentation for daux.io

### ISSUE THREAD

**Issue by dkisselev** [justinwalsh/daux.io#95]
With so many new features being added, the README file is getting a little bloated, I'd like to propose a rewrite of the readme to contain more of an overview of what daux can do as well as information on developers/how to contribute, and point people to the actual daux.io website where there will be documentation on all of the features.

I'm working on the refactor and will be supplying some documentation changes related to that but if anybody's willing to do some documentation work, I'll be happy to review/accept PR's.

So meta.

**Comment by onigoetz** [comment]
Documentation has been improved a lot already, we'll see if we need more on that
