### ISSUE TITLE
Nginx RewriteRule support

### ISSUE THREAD

**Issue by keelii** [justinwalsh/daux.io#99]
Is there any plan to support nginx RewriteRule ^!^

**Comment by devoger** [comment]
I followed all everything above and nothing works even if i disable clean url.

When I disable the clean url and add ? into the URL, it works.

http://mysite.com/index.php?/Design/Theming

My question, in which file I can edit so I can add ? in the url?

**Comment by arvidj** [comment]
clean_url enabled and keelis version worked for me. Complete config:

    server {
    	listen 80;
    	server_name docs.example.com;
    
    	index index.html index.php;
    	charset utf-8;
    
    	root /var/www/docs;
    
    	location / {
    		if (!-e $request_filename){
    			rewrite ^(.*)$ /index.php$1;
    		}
    	}
    
    	location ~ \.php {
    		fastcgi_split_path_info ^(.+\.php)(/.+)$;
    
    		fastcgi_pass unix:/var/run/php5-fpm.sock;
    		fastcgi_index index.php;
    
    		include fastcgi_params;
    		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    		fastcgi_param PATH_INFO $fastcgi_path_info;
    		fastcgi_param ENV production;
    	}
    }

**Comment by onigoetz** [comment]
Thank you @arvidj I will test this and update the documentation accordingly, did you test on the development branch or master ?

**Comment by arvidj** [comment]
Not sure actually because I use a custom version. Sorry about that!

**Comment by onigoetz** [comment]
Okay your configuration works fine, I added it to the documentation (in the development branch), thanks for your contribution

**Comment by onigoetz** [comment]
It also works fine with clean_urls
